-- Additive migration: preserves places, chapters, media_assets and Storage.
-- All editing is restricted to trusted administrative connections.
begin;
create table public.event_organizers (
 id text primary key, data jsonb not null, published boolean not null default false,
 updated_at timestamptz not null default now(), check(data->>'id'=id)
);
create table public.educational_institutions (
 id text primary key, modular_code text unique not null check(modular_code ~ '^[0-9]{7}$'),
 data jsonb not null, published boolean not null default false,
 updated_at timestamptz not null default now(), check(data->>'id'=id), check(data->>'modularCode'=modular_code)
);
create table public.calendar_events (
 id text primary key, slug text unique not null check(slug ~ '^[a-z0-9-]+$'),
 organizer_id text not null references public.event_organizers(id),
 institution_id text references public.educational_institutions(id),
 data jsonb not null, published boolean not null default false,
 updated_at timestamptz not null default now(),
 check(data->>'id'=id), check(data->>'slug'=slug), check(data->>'organizerId'=organizer_id),
 check(data->>'category' in ('Cultura','Religión','Educación','Institucional','Producción','Gastronomía','Deportes','Comunidad')),
 check(data->>'status' in ('Tradición documentada','Programa pendiente','Programa confirmado','Reprogramado','Cancelado','Finalizado')),
 check(data->'dateRule'->>'kind' in ('annual','nth-weekday','unknown','one-off'))
);
create table public.event_activities (
 id text primary key, event_id text not null references public.calendar_events(id),
 organizer_id text not null references public.event_organizers(id),
 data jsonb not null, published boolean not null default false,
 updated_at timestamptz not null default now(), check(data->>'id'=id), check(data->>'eventId'=event_id),
 check(data->>'organizerId'=organizer_id),
 check(data->>'status' in ('Tradición documentada','Programa pendiente','Programa confirmado','Reprogramado','Cancelado','Finalizado')),
 check(data->>'status' <> 'Programa confirmado' or (data->>'date' is not null and data->>'time' is not null and data->>'source' like 'https://%'))
);
create table public.event_media (
 id text primary key, event_id text not null references public.calendar_events(id),
 data jsonb not null, published boolean not null default false,
 updated_at timestamptz not null default now(), check(data->>'id'=id), check(data->>'eventId'=event_id),
 check(data->>'kind' in ('image','video')),
 check(not published or (length(data->>'author')>0 and length(data->>'license')>0 and length(data->>'authorization')>0 and data->>'source' like 'https://%'))
);
create index calendar_events_organizer_idx on public.calendar_events(organizer_id);
create index calendar_events_institution_idx on public.calendar_events(institution_id);
create index event_activities_event_idx on public.event_activities(event_id);
create index event_activities_organizer_idx on public.event_activities(organizer_id);
create index event_media_event_idx on public.event_media(event_id);
create function public.calendar_touch_updated_at() returns trigger language plpgsql set search_path = '' as $$begin new.updated_at=now(); return new; end$$;
alter table public.event_organizers enable row level security;
revoke all on public.event_organizers from anon, authenticated;
grant select on public.event_organizers to anon, authenticated;
create trigger calendar_update_timestamp before update on public.event_organizers for each row execute function public.calendar_touch_updated_at();
alter table public.educational_institutions enable row level security;
revoke all on public.educational_institutions from anon, authenticated;
grant select on public.educational_institutions to anon, authenticated;
create trigger calendar_update_timestamp before update on public.educational_institutions for each row execute function public.calendar_touch_updated_at();
alter table public.calendar_events enable row level security;
revoke all on public.calendar_events from anon, authenticated;
grant select on public.calendar_events to anon, authenticated;
create trigger calendar_update_timestamp before update on public.calendar_events for each row execute function public.calendar_touch_updated_at();
alter table public.event_activities enable row level security;
revoke all on public.event_activities from anon, authenticated;
grant select on public.event_activities to anon, authenticated;
create trigger calendar_update_timestamp before update on public.event_activities for each row execute function public.calendar_touch_updated_at();
alter table public.event_media enable row level security;
revoke all on public.event_media from anon, authenticated;
grant select on public.event_media to anon, authenticated;
create trigger calendar_update_timestamp before update on public.event_media for each row execute function public.calendar_touch_updated_at();
create policy "Read published calendar content" on public.event_organizers for select to anon, authenticated using (published);
create policy "Read published calendar content" on public.educational_institutions for select to anon, authenticated using (published);
create policy "Read published calendar content" on public.calendar_events for select to anon, authenticated using (published);
create policy "Read published children of published events" on public.event_activities for select to anon, authenticated using (published and exists(select 1 from public.calendar_events e where e.id=event_id and e.published));
create policy "Read published children of published events" on public.event_media for select to anon, authenticated using (published and exists(select 1 from public.calendar_events e where e.id=event_id and e.published));
insert into public.event_organizers (id,data,published) values ('municipalidad','{"id": "municipalidad", "name": "Municipalidad Distrital de Huayopata", "url": "https://www.gob.pe/munihuayopata"}'::jsonb,true) on conflict(id) do nothing;
insert into public.event_organizers (id,data,published) values ('local','{"id": "local", "name": "Organización local por confirmar", "url": null}'::jsonb,true) on conflict(id) do nothing;
insert into public.event_organizers (id,data,published) values ('minedu','{"id": "minedu", "name": "MINEDU · referencia nacional", "url": "https://www.gob.pe/minedu"}'::jsonb,true) on conflict(id) do nothing;
insert into public.event_organizers (id,data,published) values ('ie-0236380','{"id": "ie-0236380", "name": "I. E. José Carlos Mariátegui", "url": null}'::jsonb,true) on conflict(id) do nothing;
insert into public.event_organizers (id,data,published) values ('ie-0407619','{"id": "ie-0407619", "name": "I. E. 50275", "url": null}'::jsonb,true) on conflict(id) do nothing;
insert into public.event_organizers (id,data,published) values ('ie-0621367','{"id": "ie-0621367", "name": "I. E. Leoncio Prado", "url": null}'::jsonb,true) on conflict(id) do nothing;
insert into public.event_organizers (id,data,published) values ('ie-0699678','{"id": "ie-0699678", "name": "I. E. Coronel Francisco Bolognesi", "url": null}'::jsonb,true) on conflict(id) do nothing;
insert into public.event_organizers (id,data,published) values ('ie-0407460','{"id": "ie-0407460", "name": "I. E. 50260", "url": null}'::jsonb,true) on conflict(id) do nothing;
insert into public.event_organizers (id,data,published) values ('ie-0407478','{"id": "ie-0407478", "name": "I. E. 50261", "url": null}'::jsonb,true) on conflict(id) do nothing;
insert into public.event_organizers (id,data,published) values ('ie-0407601','{"id": "ie-0407601", "name": "I. E. 50274", "url": null}'::jsonb,true) on conflict(id) do nothing;
insert into public.event_organizers (id,data,published) values ('ie-0205229','{"id": "ie-0205229", "name": "I. E. 50748", "url": null}'::jsonb,true) on conflict(id) do nothing;
insert into public.event_organizers (id,data,published) values ('ie-0205252','{"id": "ie-0205252", "name": "I. E. 50751", "url": null}'::jsonb,true) on conflict(id) do nothing;
insert into public.event_organizers (id,data,published) values ('ie-0615377','{"id": "ie-0615377", "name": "I. E. 501093", "url": null}'::jsonb,true) on conflict(id) do nothing;
insert into public.educational_institutions (id,data,published,modular_code) values ('ie-0236380','{"id": "ie-0236380", "name": "I. E. José Carlos Mariátegui", "modularCode": "0236380", "locality": "Huyro", "level": "Secundaria", "anniversary": "06-14", "anniversaryStatus": "14 de junio · fecha documentada en 2018", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}, {"label": "Congreso de la República: Diario de Debates, 2018, página 44 (PDF página 43): Bodas de Oro el 14 de junio de 2018", "url": "https://www3.congreso.gob.pe/Docs/DGP/diariodebates/files/aprobacion-insistencia/slo-2017-17a.pdf", "kind": "Referencia institucional histórica", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "note": "La UGEL identifica esta institución en Huyro. El Congreso documenta sus Bodas de Oro el 14 de junio de 2018. Programa de la próxima edición pendiente."}'::jsonb,true,'0236380') on conflict(id) do nothing;
insert into public.educational_institutions (id,data,published,modular_code) values ('ie-0407619','{"id": "ie-0407619", "name": "I. E. 50275", "modularCode": "0407619", "locality": "Huyro", "level": "Primaria", "anniversary": null, "anniversaryStatus": "Fecha por confirmar", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "note": "Identificación documental UGEL 2022. Localidad normalizada: el registro escribe Huayopata para Leoncio Prado e Ipalpilhua para 50274. Aniversario y vigencia actual por validar con la institución."}'::jsonb,true,'0407619') on conflict(id) do nothing;
insert into public.educational_institutions (id,data,published,modular_code) values ('ie-0621367','{"id": "ie-0621367", "name": "I. E. Leoncio Prado", "modularCode": "0621367", "locality": "Huayopata Rodeo", "level": "Secundaria", "anniversary": null, "anniversaryStatus": "Fecha por confirmar", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "note": "Identificación documental UGEL 2022. Localidad normalizada: el registro escribe Huayopata para Leoncio Prado e Ipalpilhua para 50274. Aniversario y vigencia actual por validar con la institución."}'::jsonb,true,'0621367') on conflict(id) do nothing;
insert into public.educational_institutions (id,data,published,modular_code) values ('ie-0699678','{"id": "ie-0699678", "name": "I. E. Coronel Francisco Bolognesi", "modularCode": "0699678", "locality": "Amaybamba", "level": "Secundaria", "anniversary": null, "anniversaryStatus": "Fecha por confirmar", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "note": "Identificación documental UGEL 2022. Localidad normalizada: el registro escribe Huayopata para Leoncio Prado e Ipalpilhua para 50274. Aniversario y vigencia actual por validar con la institución."}'::jsonb,true,'0699678') on conflict(id) do nothing;
insert into public.educational_institutions (id,data,published,modular_code) values ('ie-0407460','{"id": "ie-0407460", "name": "I. E. 50260", "modularCode": "0407460", "locality": "San Pablo", "level": "Primaria", "anniversary": null, "anniversaryStatus": "Fecha por confirmar", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "note": "Identificación documental UGEL 2022. Localidad normalizada: el registro escribe Huayopata para Leoncio Prado e Ipalpilhua para 50274. Aniversario y vigencia actual por validar con la institución."}'::jsonb,true,'0407460') on conflict(id) do nothing;
insert into public.educational_institutions (id,data,published,modular_code) values ('ie-0407478','{"id": "ie-0407478", "name": "I. E. 50261", "modularCode": "0407478", "locality": "Lauramarca", "level": "Primaria", "anniversary": null, "anniversaryStatus": "Fecha por confirmar", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "note": "Identificación documental UGEL 2022. Localidad normalizada: el registro escribe Huayopata para Leoncio Prado e Ipalpilhua para 50274. Aniversario y vigencia actual por validar con la institución."}'::jsonb,true,'0407478') on conflict(id) do nothing;
insert into public.educational_institutions (id,data,published,modular_code) values ('ie-0407601','{"id": "ie-0407601", "name": "I. E. 50274", "modularCode": "0407601", "locality": "Ipal Pirhua", "level": "Primaria", "anniversary": null, "anniversaryStatus": "Fecha por confirmar", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "note": "Identificación documental UGEL 2022. Localidad normalizada: el registro escribe Huayopata para Leoncio Prado e Ipalpilhua para 50274. Aniversario y vigencia actual por validar con la institución."}'::jsonb,true,'0407601') on conflict(id) do nothing;
insert into public.educational_institutions (id,data,published,modular_code) values ('ie-0205229','{"id": "ie-0205229", "name": "I. E. 50748", "modularCode": "0205229", "locality": "Alfamayo", "level": "Primaria", "anniversary": null, "anniversaryStatus": "Fecha por confirmar", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "note": "Identificación documental UGEL 2022. Localidad normalizada: el registro escribe Huayopata para Leoncio Prado e Ipalpilhua para 50274. Aniversario y vigencia actual por validar con la institución."}'::jsonb,true,'0205229') on conflict(id) do nothing;
insert into public.educational_institutions (id,data,published,modular_code) values ('ie-0205252','{"id": "ie-0205252", "name": "I. E. 50751", "modularCode": "0205252", "locality": "Amaybamba", "level": "Primaria", "anniversary": null, "anniversaryStatus": "Fecha por confirmar", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "note": "Identificación documental UGEL 2022. Localidad normalizada: el registro escribe Huayopata para Leoncio Prado e Ipalpilhua para 50274. Aniversario y vigencia actual por validar con la institución."}'::jsonb,true,'0205252') on conflict(id) do nothing;
insert into public.educational_institutions (id,data,published,modular_code) values ('ie-0615377','{"id": "ie-0615377", "name": "I. E. 501093", "modularCode": "0615377", "locality": "Huamanmarca", "level": "Primaria", "anniversary": null, "anniversaryStatus": "Fecha por confirmar", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "note": "Identificación documental UGEL 2022. Localidad normalizada: el registro escribe Huayopata para Leoncio Prado e Ipalpilhua para 50274. Aniversario y vigencia actual por validar con la institución."}'::jsonb,true,'0615377') on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('unu-raymi','{"id": "unu-raymi", "slug": "unu-raymi", "title": "Unu Raymi · Fiesta del Agua", "category": "Cultura", "locality": "Pasto Grande · San Pablo · Huyro", "organizerId": "municipalidad", "institutionId": null, "dateRule": {"kind": "annual", "month": 3, "day": 22}, "status": "Tradición documentada", "summary": "Un encuentro en torno al agua y al territorio. El inventario turístico registra un recorrido ceremonial entre Pasto Grande, San Pablo y Huyro.", "history": "Un encuentro en torno al agua y al territorio. El inventario turístico registra un recorrido ceremonial entre Pasto Grande, San Pablo y Huyro.", "editorialNote": "Fecha de referencia tradicional. El programa de la próxima edición todavía no está confirmado. Consulta a los organizadores antes de viajar.", "sources": [{"label": "MINCETUR / GERCETUR: Unu Raymi", "url": "https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=13023", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [{"year": 2023, "description": "El inventario documenta una escenificación y el recorrido ceremonial de 2023. Es un registro histórico, no el programa de una edición futura.", "source": "https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=13023"}], "published": true}'::jsonb,true,'unu-raymi','municipalidad',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('huamanmarca-raymi','{"id": "huamanmarca-raymi", "slug": "huamanmarca-raymi", "title": "Huamanmarca Raymi", "category": "Cultura", "locality": "Huamanmarca", "organizerId": "municipalidad", "institutionId": null, "dateRule": {"kind": "nth-weekday", "month": 6, "weekday": 0, "nth": 2}, "status": "Tradición documentada", "summary": "La escenificación del legado histórico del distrito tiene lugar en Wamanmarka. La ficha institucional sitúa la celebración el segundo domingo de junio y describe encuentros de danza y cocina local.", "history": "La escenificación del legado histórico del distrito tiene lugar en Wamanmarka. La ficha institucional sitúa la celebración el segundo domingo de junio y describe encuentros de danza y cocina local.", "editorialNote": "Fecha de referencia tradicional. El programa de la próxima edición todavía no está confirmado. Consulta a los organizadores antes de viajar.", "sources": [{"label": "MINCETUR / GERCETUR: Huamanmarca Raymi, ficha 2024", "url": "https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=12953", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "wamanmarka", "location": {"lat": -13.02074, "lng": -72.49567, "label": "Referencia general del sitio arqueológico; no identifica el escenario ni el acceso", "source": "https://www.openstreetmap.org/way/771625883"}, "editions": [], "published": true}'::jsonb,true,'huamanmarca-raymi','municipalidad',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('aniversario-huayopata','{"id": "aniversario-huayopata", "slug": "aniversario-huayopata", "title": "Aniversario del distrito de Huayopata", "category": "Institucional", "locality": "Huyro · distrito de Huayopata", "organizerId": "municipalidad", "institutionId": null, "dateRule": {"kind": "annual", "month": 6, "day": 19}, "status": "Tradición documentada", "summary": "El distrito celebra su aniversario el 19 de junio. Las instituciones y comunidades se encuentran para conmemorar la vida del distrito; cada gestión publica su propio programa.", "history": "El distrito celebra su aniversario el 19 de junio. Las instituciones y comunidades se encuentran para conmemorar la vida del distrito; cada gestión publica su propio programa.", "editorialNote": "Fecha de referencia tradicional. El programa de la próxima edición todavía no está confirmado. Consulta a los organizadores antes de viajar.", "sources": [{"label": "Municipalidad Provincial de La Convención: saludo institucional 2025", "url": "https://www.gob.pe/institucion/munilaconvencion/normas-legales/6873402-332-2025-mplc-a", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'aniversario-huayopata','municipalidad',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('virgen-del-carmen','{"id": "virgen-del-carmen", "slug": "virgen-del-carmen", "title": "Virgen del Carmen de Huyro", "category": "Religión", "locality": "Huyro · Amaybamba", "organizerId": "local", "institutionId": null, "dateRule": {"kind": "annual", "month": 7, "day": 16}, "status": "Tradición documentada", "summary": "La Virgen del Carmen es reconocida como patrona local. La ficha turística oficial ubica su fecha central el 16 de julio y su referencia en la Plaza Mayor de Huyro.", "history": "La Virgen del Carmen es reconocida como patrona local. La ficha turística oficial ubica su fecha central el 16 de julio y su referencia en la Plaza Mayor de Huyro.", "editorialNote": "Fecha de referencia tradicional. El programa de la próxima edición todavía no está confirmado. Consulta a los organizadores antes de viajar.", "sources": [{"label": "MINCETUR / GERCETUR: Virgen del Carmen", "url": "https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=13004", "kind": "Institucional", "accessedAt": "2026-09-29"}, {"label": "Calendario local recogido en la investigación de Aguilar Solís e Izquierdo Calderón (2017), tabla 16", "url": "https://es.scribd.com/document/389871947/TESIS", "kind": "Referencia histórica; vigencia por confirmar", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'virgen-del-carmen','local',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('watunakuy','{"id": "watunakuy", "slug": "watunakuy", "title": "Watunakuy", "category": "Comunidad", "locality": "Huamanmarca", "organizerId": "local", "institutionId": null, "dateRule": {"kind": "unknown"}, "status": "Tradición documentada", "summary": "Un encuentro tradicional alrededor de las semillas y la relación con la tierra, registrado en el inventario turístico de Wamanmarka.", "history": "Un encuentro tradicional alrededor de las semillas y la relación con la tierra, registrado en el inventario turístico de Wamanmarka.", "editorialNote": "Fecha variable. El inventario menciona agosto, mientras que un programa de 2021 lo incluye en junio. No se asigna un día hasta disponer del anuncio de la edición.", "sources": [{"label": "MINCETUR / GERCETUR: Wamanmarka", "url": "https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=6915", "kind": "Institucional", "accessedAt": "2026-09-29"}, {"label": "Programa histórico del aniversario, 2021", "url": "https://viajandoporperu.com/2021/06/14/cusco-programa-del-164-aniversario-de-huayopata/", "kind": "Archivo periodístico", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "wamanmarka", "location": null, "editions": [], "published": true}'::jsonb,true,'watunakuy','local',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('expoferia-huayopata','{"id": "expoferia-huayopata", "slug": "expoferia-huayopata", "title": "Expoferia Huayopata", "category": "Producción", "locality": "Huyro", "organizerId": "municipalidad", "institutionId": null, "dateRule": {"kind": "unknown"}, "status": "Tradición documentada", "summary": "Productores del distrito presentan café, té, chocolate y producción agropecuaria. El inventario también describe gastronomía, danzas y pasacalles en el Estadio Municipal de Huyro.", "history": "Productores del distrito presentan café, té, chocolate y producción agropecuaria. El inventario también describe gastronomía, danzas y pasacalles en el Estadio Municipal de Huyro.", "editorialNote": "Fecha de la siguiente edición por confirmar. La descripción del inventario no constituye una convocatoria ni un programa vigente.", "sources": [{"label": "MINCETUR / GERCETUR: Expoferia Huayopata", "url": "https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=13024", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'expoferia-huayopata','municipalidad',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('virgen-candelaria','{"id": "virgen-candelaria", "slug": "virgen-candelaria", "title": "Virgen de la Candelaria", "category": "Religión", "locality": "Distrito de Huayopata", "organizerId": "local", "institutionId": null, "dateRule": {"kind": "annual", "month": 2, "day": 2}, "status": "Tradición documentada", "summary": "El calendario local recogido en 2017 registra esta celebración en Distrito de Huayopata. Su continuidad, responsables y programa actual requieren confirmación local.", "history": "El calendario local recogido en 2017 registra esta celebración en Distrito de Huayopata. Su continuidad, responsables y programa actual requieren confirmación local.", "editorialNote": "Fecha y localidad de referencia histórica (2017); vigencia por confirmar con la comunidad. No existe un programa actual publicado en este calendario.", "sources": [{"label": "Calendario local recogido en la investigación de Aguilar Solís e Izquierdo Calderón (2017), tabla 16", "url": "https://es.scribd.com/document/389871947/TESIS", "kind": "Referencia histórica; vigencia por confirmar", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'virgen-candelaria','local',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('santisima-cruz','{"id": "santisima-cruz", "slug": "santisima-cruz", "title": "Santísima Cruz", "category": "Religión", "locality": "Distrito de Huayopata", "organizerId": "local", "institutionId": null, "dateRule": {"kind": "annual", "month": 5, "day": 3}, "status": "Tradición documentada", "summary": "El calendario local recogido en 2017 registra esta celebración en Distrito de Huayopata. Su continuidad, responsables y programa actual requieren confirmación local.", "history": "El calendario local recogido en 2017 registra esta celebración en Distrito de Huayopata. Su continuidad, responsables y programa actual requieren confirmación local.", "editorialNote": "Fecha y localidad de referencia histórica (2017); vigencia por confirmar con la comunidad. No existe un programa actual publicado en este calendario.", "sources": [{"label": "Calendario local recogido en la investigación de Aguilar Solís e Izquierdo Calderón (2017), tabla 16", "url": "https://es.scribd.com/document/389871947/TESIS", "kind": "Referencia histórica; vigencia por confirmar", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'santisima-cruz','local',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('virgen-asunta','{"id": "virgen-asunta", "slug": "virgen-asunta", "title": "Virgen Asunta", "category": "Religión", "locality": "Huyro", "organizerId": "local", "institutionId": null, "dateRule": {"kind": "annual", "month": 8, "day": 15}, "status": "Tradición documentada", "summary": "El calendario local recogido en 2017 registra esta celebración en Huyro. Su continuidad, responsables y programa actual requieren confirmación local.", "history": "El calendario local recogido en 2017 registra esta celebración en Huyro. Su continuidad, responsables y programa actual requieren confirmación local.", "editorialNote": "Fecha y localidad de referencia histórica (2017); vigencia por confirmar con la comunidad. No existe un programa actual publicado en este calendario.", "sources": [{"label": "Calendario local recogido en la investigación de Aguilar Solís e Izquierdo Calderón (2017), tabla 16", "url": "https://es.scribd.com/document/389871947/TESIS", "kind": "Referencia histórica; vigencia por confirmar", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'virgen-asunta','local',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('santa-rosa','{"id": "santa-rosa", "slug": "santa-rosa", "title": "Santa Rosa", "category": "Religión", "locality": "Distrito de Huayopata", "organizerId": "local", "institutionId": null, "dateRule": {"kind": "annual", "month": 8, "day": 30}, "status": "Tradición documentada", "summary": "El calendario local recogido en 2017 registra esta celebración en Distrito de Huayopata. Su continuidad, responsables y programa actual requieren confirmación local.", "history": "El calendario local recogido en 2017 registra esta celebración en Distrito de Huayopata. Su continuidad, responsables y programa actual requieren confirmación local.", "editorialNote": "Fecha y localidad de referencia histórica (2017); vigencia por confirmar con la comunidad. No existe un programa actual publicado en este calendario.", "sources": [{"label": "Calendario local recogido en la investigación de Aguilar Solís e Izquierdo Calderón (2017), tabla 16", "url": "https://es.scribd.com/document/389871947/TESIS", "kind": "Referencia histórica; vigencia por confirmar", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'santa-rosa','local',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('senor-huanca','{"id": "senor-huanca", "slug": "senor-huanca", "title": "Señor de Huanca", "category": "Religión", "locality": "Distrito de Huayopata", "organizerId": "local", "institutionId": null, "dateRule": {"kind": "annual", "month": 9, "day": 14}, "status": "Tradición documentada", "summary": "El calendario local recogido en 2017 registra esta celebración en Distrito de Huayopata. Su continuidad, responsables y programa actual requieren confirmación local.", "history": "El calendario local recogido en 2017 registra esta celebración en Distrito de Huayopata. Su continuidad, responsables y programa actual requieren confirmación local.", "editorialNote": "Fecha y localidad de referencia histórica (2017); vigencia por confirmar con la comunidad. No existe un programa actual publicado en este calendario.", "sources": [{"label": "Calendario local recogido en la investigación de Aguilar Solís e Izquierdo Calderón (2017), tabla 16", "url": "https://es.scribd.com/document/389871947/TESIS", "kind": "Referencia histórica; vigencia por confirmar", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'senor-huanca','local',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('san-cipriano','{"id": "san-cipriano", "slug": "san-cipriano", "title": "San Cipriano", "category": "Religión", "locality": "Sicre", "organizerId": "local", "institutionId": null, "dateRule": {"kind": "annual", "month": 9, "day": 23}, "status": "Tradición documentada", "summary": "El calendario local recogido en 2017 registra esta celebración en Sicre. Su continuidad, responsables y programa actual requieren confirmación local.", "history": "El calendario local recogido en 2017 registra esta celebración en Sicre. Su continuidad, responsables y programa actual requieren confirmación local.", "editorialNote": "Fecha y localidad de referencia histórica (2017); vigencia por confirmar con la comunidad. No existe un programa actual publicado en este calendario.", "sources": [{"label": "Calendario local recogido en la investigación de Aguilar Solís e Izquierdo Calderón (2017), tabla 16", "url": "https://es.scribd.com/document/389871947/TESIS", "kind": "Referencia histórica; vigencia por confirmar", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'san-cipriano','local',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('virgen-fatima','{"id": "virgen-fatima", "slug": "virgen-fatima", "title": "Virgen de Fátima", "category": "Religión", "locality": "Huayopata Chonta", "organizerId": "local", "institutionId": null, "dateRule": {"kind": "annual", "month": 10, "day": 13}, "status": "Tradición documentada", "summary": "El calendario local recogido en 2017 registra esta celebración en Huayopata Chonta. Su continuidad, responsables y programa actual requieren confirmación local.", "history": "El calendario local recogido en 2017 registra esta celebración en Huayopata Chonta. Su continuidad, responsables y programa actual requieren confirmación local.", "editorialNote": "Fecha y localidad de referencia histórica (2017); vigencia por confirmar con la comunidad. No existe un programa actual publicado en este calendario.", "sources": [{"label": "Calendario local recogido en la investigación de Aguilar Solís e Izquierdo Calderón (2017), tabla 16", "url": "https://es.scribd.com/document/389871947/TESIS", "kind": "Referencia histórica; vigencia por confirmar", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'virgen-fatima','local',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('senor-milagros','{"id": "senor-milagros", "slug": "senor-milagros", "title": "Señor de los Milagros", "category": "Religión", "locality": "Amaybamba", "organizerId": "local", "institutionId": null, "dateRule": {"kind": "annual", "month": 10, "day": 18}, "status": "Tradición documentada", "summary": "El calendario local recogido en 2017 registra esta celebración en Amaybamba. Su continuidad, responsables y programa actual requieren confirmación local.", "history": "El calendario local recogido en 2017 registra esta celebración en Amaybamba. Su continuidad, responsables y programa actual requieren confirmación local.", "editorialNote": "Fecha y localidad de referencia histórica (2017); vigencia por confirmar con la comunidad. No existe un programa actual publicado en este calendario.", "sources": [{"label": "Calendario local recogido en la investigación de Aguilar Solís e Izquierdo Calderón (2017), tabla 16", "url": "https://es.scribd.com/document/389871947/TESIS", "kind": "Referencia histórica; vigencia por confirmar", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'senor-milagros','local',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('todos-santos','{"id": "todos-santos", "slug": "todos-santos", "title": "Todos los Santos", "category": "Religión", "locality": "Distrito de Huayopata", "organizerId": "local", "institutionId": null, "dateRule": {"kind": "annual", "month": 11, "day": 1}, "status": "Tradición documentada", "summary": "El calendario local recogido en 2017 registra esta celebración en Distrito de Huayopata. Su continuidad, responsables y programa actual requieren confirmación local.", "history": "El calendario local recogido en 2017 registra esta celebración en Distrito de Huayopata. Su continuidad, responsables y programa actual requieren confirmación local.", "editorialNote": "Fecha y localidad de referencia histórica (2017); vigencia por confirmar con la comunidad. No existe un programa actual publicado en este calendario.", "sources": [{"label": "Calendario local recogido en la investigación de Aguilar Solís e Izquierdo Calderón (2017), tabla 16", "url": "https://es.scribd.com/document/389871947/TESIS", "kind": "Referencia histórica; vigencia por confirmar", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'todos-santos','local',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('san-martin-porres','{"id": "san-martin-porres", "slug": "san-martin-porres", "title": "San Martín de Porres", "category": "Religión", "locality": "Zorrapata", "organizerId": "local", "institutionId": null, "dateRule": {"kind": "annual", "month": 11, "day": 3}, "status": "Tradición documentada", "summary": "El calendario local recogido en 2017 registra esta celebración en Zorrapata. Su continuidad, responsables y programa actual requieren confirmación local.", "history": "El calendario local recogido en 2017 registra esta celebración en Zorrapata. Su continuidad, responsables y programa actual requieren confirmación local.", "editorialNote": "Fecha y localidad de referencia histórica (2017); vigencia por confirmar con la comunidad. No existe un programa actual publicado en este calendario.", "sources": [{"label": "Calendario local recogido en la investigación de Aguilar Solís e Izquierdo Calderón (2017), tabla 16", "url": "https://es.scribd.com/document/389871947/TESIS", "kind": "Referencia histórica; vigencia por confirmar", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'san-martin-porres','local',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('aniversario-ie-0236380','{"id": "aniversario-ie-0236380", "slug": "aniversario-ie-0236380", "title": "Aniversario · I. E. José Carlos Mariátegui", "category": "Educación", "locality": "Huyro", "organizerId": "ie-0236380", "institutionId": "ie-0236380", "dateRule": {"kind": "annual", "month": 6, "day": 14}, "status": "Programa pendiente", "summary": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "history": "El Congreso de la República saludó a la I. E. José Carlos Mariátegui de Huyro por sus Bodas de Oro el 14 de junio de 2018. La fecha se incorpora como referencia institucional histórica, sin anunciar actividades futuras.", "editorialNote": "Aniversario documentado el 14 de junio de 2018 (Bodas de Oro). Fecha de referencia anual; programa actual pendiente de la dirección.", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}, {"label": "Congreso de la República: Diario de Debates, 2018, página 44 (PDF página 43): Bodas de Oro el 14 de junio de 2018", "url": "https://www3.congreso.gob.pe/Docs/DGP/diariodebates/files/aprobacion-insistencia/slo-2017-17a.pdf", "kind": "Referencia institucional histórica", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [{"year": 2018, "description": "Bodas de Oro de la institución, documentadas en el saludo del Congreso. No se dispone del programa de actividades.", "source": "https://www3.congreso.gob.pe/Docs/DGP/diariodebates/files/aprobacion-insistencia/slo-2017-17a.pdf"}], "published": true}'::jsonb,true,'aniversario-ie-0236380','ie-0236380','ie-0236380') on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('aniversario-ie-0407619','{"id": "aniversario-ie-0407619", "slug": "aniversario-ie-0407619", "title": "Aniversario · I. E. 50275", "category": "Educación", "locality": "Huyro", "organizerId": "ie-0407619", "institutionId": "ie-0407619", "dateRule": {"kind": "unknown"}, "status": "Programa pendiente", "summary": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "history": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "editorialNote": "Fecha por confirmar. No se han documentado concursos, horarios ni actividades de una próxima edición.", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'aniversario-ie-0407619','ie-0407619','ie-0407619') on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('aniversario-ie-0621367','{"id": "aniversario-ie-0621367", "slug": "aniversario-ie-0621367", "title": "Aniversario · I. E. Leoncio Prado", "category": "Educación", "locality": "Huayopata Rodeo", "organizerId": "ie-0621367", "institutionId": "ie-0621367", "dateRule": {"kind": "unknown"}, "status": "Programa pendiente", "summary": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "history": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "editorialNote": "Fecha por confirmar. No se han documentado concursos, horarios ni actividades de una próxima edición.", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'aniversario-ie-0621367','ie-0621367','ie-0621367') on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('aniversario-ie-0699678','{"id": "aniversario-ie-0699678", "slug": "aniversario-ie-0699678", "title": "Aniversario · I. E. Coronel Francisco Bolognesi", "category": "Educación", "locality": "Amaybamba", "organizerId": "ie-0699678", "institutionId": "ie-0699678", "dateRule": {"kind": "unknown"}, "status": "Programa pendiente", "summary": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "history": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "editorialNote": "Fecha por confirmar. No se han documentado concursos, horarios ni actividades de una próxima edición.", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'aniversario-ie-0699678','ie-0699678','ie-0699678') on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('aniversario-ie-0407460','{"id": "aniversario-ie-0407460", "slug": "aniversario-ie-0407460", "title": "Aniversario · I. E. 50260", "category": "Educación", "locality": "San Pablo", "organizerId": "ie-0407460", "institutionId": "ie-0407460", "dateRule": {"kind": "unknown"}, "status": "Programa pendiente", "summary": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "history": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "editorialNote": "Fecha por confirmar. No se han documentado concursos, horarios ni actividades de una próxima edición.", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'aniversario-ie-0407460','ie-0407460','ie-0407460') on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('aniversario-ie-0407478','{"id": "aniversario-ie-0407478", "slug": "aniversario-ie-0407478", "title": "Aniversario · I. E. 50261", "category": "Educación", "locality": "Lauramarca", "organizerId": "ie-0407478", "institutionId": "ie-0407478", "dateRule": {"kind": "unknown"}, "status": "Programa pendiente", "summary": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "history": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "editorialNote": "Fecha por confirmar. No se han documentado concursos, horarios ni actividades de una próxima edición.", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'aniversario-ie-0407478','ie-0407478','ie-0407478') on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('aniversario-ie-0407601','{"id": "aniversario-ie-0407601", "slug": "aniversario-ie-0407601", "title": "Aniversario · I. E. 50274", "category": "Educación", "locality": "Ipal Pirhua", "organizerId": "ie-0407601", "institutionId": "ie-0407601", "dateRule": {"kind": "unknown"}, "status": "Programa pendiente", "summary": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "history": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "editorialNote": "Fecha por confirmar. No se han documentado concursos, horarios ni actividades de una próxima edición.", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'aniversario-ie-0407601','ie-0407601','ie-0407601') on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('aniversario-ie-0205229','{"id": "aniversario-ie-0205229", "slug": "aniversario-ie-0205229", "title": "Aniversario · I. E. 50748", "category": "Educación", "locality": "Alfamayo", "organizerId": "ie-0205229", "institutionId": "ie-0205229", "dateRule": {"kind": "unknown"}, "status": "Programa pendiente", "summary": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "history": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "editorialNote": "Fecha por confirmar. No se han documentado concursos, horarios ni actividades de una próxima edición.", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'aniversario-ie-0205229','ie-0205229','ie-0205229') on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('aniversario-ie-0205252','{"id": "aniversario-ie-0205252", "slug": "aniversario-ie-0205252", "title": "Aniversario · I. E. 50751", "category": "Educación", "locality": "Amaybamba", "organizerId": "ie-0205252", "institutionId": "ie-0205252", "dateRule": {"kind": "unknown"}, "status": "Programa pendiente", "summary": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "history": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "editorialNote": "Fecha por confirmar. No se han documentado concursos, horarios ni actividades de una próxima edición.", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'aniversario-ie-0205252','ie-0205252','ie-0205252') on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('aniversario-ie-0615377','{"id": "aniversario-ie-0615377", "slug": "aniversario-ie-0615377", "title": "Aniversario · I. E. 501093", "category": "Educación", "locality": "Huamanmarca", "organizerId": "ie-0615377", "institutionId": "ie-0615377", "dateRule": {"kind": "unknown"}, "status": "Programa pendiente", "summary": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "history": "Ficha institucional para incorporar el aniversario y sus actividades culturales, deportivas y educativas cuando la dirección confirme fecha y programa.", "editorialNote": "Fecha por confirmar. No se han documentado concursos, horarios ni actividades de una próxima edición.", "sources": [{"label": "UGEL La Convención: distribución de materiales educativos, 2022", "url": "https://www.ugellaconvencion.gob.pe/lc/doc_2022/abast_2022/035_PC_TRAMO_01_CONTRATACION_SERVICIOS_TRANSPORTE_REDISTRIBUCION_ME_SE_D2022.pdf", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'aniversario-ie-0615377','ie-0615377','ie-0615377') on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('educacion-inicial','{"id": "educacion-inicial", "slug": "educacion-inicial", "title": "Día de la Educación Inicial", "category": "Educación", "locality": "Distrito de Huayopata · referencia nacional", "organizerId": "minedu", "institutionId": null, "dateRule": {"kind": "annual", "month": 5, "day": 25}, "status": "Tradición documentada", "summary": "Fecha del calendario educativo peruano. Las actividades de las instituciones de Huayopata se incorporarán cuando exista confirmación local.", "history": "Fecha del calendario educativo peruano. Las actividades de las instituciones de Huayopata se incorporarán cuando exista confirmación local.", "editorialNote": "Efeméride nacional. No equivale a una actividad local convocada; programa en Huayopata pendiente.", "sources": [{"label": "MINEDU: aniversario de Educación Inicial, 2026", "url": "https://www.gob.pe/institucion/minedu/noticias/1397160-minedu-destaca-avances-y-desafios-de-la-educacion-inicial-en-el-marco-de-sus-95-anos", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'educacion-inicial','minedu',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('educacion-primaria','{"id": "educacion-primaria", "slug": "educacion-primaria", "title": "Día de la Educación Primaria", "category": "Educación", "locality": "Distrito de Huayopata · referencia nacional", "organizerId": "minedu", "institutionId": null, "dateRule": {"kind": "annual", "month": 11, "day": 12}, "status": "Tradición documentada", "summary": "Fecha del calendario educativo peruano. Las actividades de las instituciones de Huayopata se incorporarán cuando exista confirmación local.", "history": "Fecha del calendario educativo peruano. Las actividades de las instituciones de Huayopata se incorporarán cuando exista confirmación local.", "editorialNote": "Efeméride nacional. No equivale a una actividad local convocada; programa en Huayopata pendiente.", "sources": [{"label": "MINEDU: Resolución Ministerial 460-2022", "url": "https://www.gob.pe/institucion/minedu/normas-legales/3650725-460-2022-minedu", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'educacion-primaria','minedu',null) on conflict(id) do nothing;
insert into public.calendar_events (id,data,published,slug,organizer_id,institution_id) values ('educacion-secundaria','{"id": "educacion-secundaria", "slug": "educacion-secundaria", "title": "Día de la Educación Secundaria", "category": "Educación", "locality": "Distrito de Huayopata · referencia nacional", "organizerId": "minedu", "institutionId": null, "dateRule": {"kind": "annual", "month": 10, "day": 27}, "status": "Tradición documentada", "summary": "Fecha del calendario educativo peruano. Las actividades de las instituciones de Huayopata se incorporarán cuando exista confirmación local.", "history": "Fecha del calendario educativo peruano. Las actividades de las instituciones de Huayopata se incorporarán cuando exista confirmación local.", "editorialNote": "Efeméride nacional. No equivale a una actividad local convocada; programa en Huayopata pendiente.", "sources": [{"label": "MINEDU: Resolución Ministerial 436-2024", "url": "https://www.gob.pe/institucion/minedu/normas-legales/5943357-436-2024-minedu", "kind": "Institucional", "accessedAt": "2026-09-29"}], "updatedAt": "2026-09-29", "photoPending": true, "relatedTopic": "comunidades", "location": null, "editions": [], "published": true}'::jsonb,true,'educacion-secundaria','minedu',null) on conflict(id) do nothing;
insert into public.event_activities (id,data,published,event_id,organizer_id) values ('huamanmarca-raymi-0','{"id": "huamanmarca-raymi-0", "eventId": "huamanmarca-raymi", "name": "Escenificación histórica", "date": null, "time": null, "place": "Sitio arqueológico de Wamanmarka", "description": "Componente descrito en el inventario turístico. Fecha, horario y realización de una próxima edición por confirmar.", "category": "Cultura", "organizerId": "municipalidad", "status": "Tradición documentada", "source": "https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=12953", "published": true}'::jsonb,true,'huamanmarca-raymi','municipalidad') on conflict(id) do nothing;
insert into public.event_activities (id,data,published,event_id,organizer_id) values ('huamanmarca-raymi-1','{"id": "huamanmarca-raymi-1", "eventId": "huamanmarca-raymi", "name": "Concurso de danzas de instituciones educativas", "date": null, "time": null, "place": "Cancha de la institución educativa del sector Huamanmarca", "description": "Componente descrito en el inventario turístico. Fecha, horario y realización de una próxima edición por confirmar.", "category": "Educación", "organizerId": "municipalidad", "status": "Tradición documentada", "source": "https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=12953", "published": true}'::jsonb,true,'huamanmarca-raymi','municipalidad') on conflict(id) do nothing;
insert into public.event_activities (id,data,published,event_id,organizer_id) values ('huamanmarca-raymi-2','{"id": "huamanmarca-raymi-2", "eventId": "huamanmarca-raymi", "name": "Muestra de comidas locales", "date": null, "time": null, "place": "Sector Huamanmarca", "description": "Componente descrito en el inventario turístico. Fecha, horario y realización de una próxima edición por confirmar.", "category": "Gastronomía", "organizerId": "municipalidad", "status": "Tradición documentada", "source": "https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=12953", "published": true}'::jsonb,true,'huamanmarca-raymi','municipalidad') on conflict(id) do nothing;
insert into public.event_activities (id,data,published,event_id,organizer_id) values ('expoferia-huayopata-0','{"id": "expoferia-huayopata-0", "eventId": "expoferia-huayopata", "name": "Exposición agroindustrial y agropecuaria", "date": null, "time": null, "place": "Estadio Municipal de Huyro", "description": "Componente descrito en el inventario turístico. Fecha, horario y realización de una próxima edición por confirmar.", "category": "Producción", "organizerId": "municipalidad", "status": "Tradición documentada", "source": "https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=13024", "published": true}'::jsonb,true,'expoferia-huayopata','municipalidad') on conflict(id) do nothing;
insert into public.event_activities (id,data,published,event_id,organizer_id) values ('expoferia-huayopata-1','{"id": "expoferia-huayopata-1", "eventId": "expoferia-huayopata", "name": "Encuentro gastronómico", "date": null, "time": null, "place": "Estadio Municipal de Huyro", "description": "Componente descrito en el inventario turístico. Fecha, horario y realización de una próxima edición por confirmar.", "category": "Gastronomía", "organizerId": "municipalidad", "status": "Tradición documentada", "source": "https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=13024", "published": true}'::jsonb,true,'expoferia-huayopata','municipalidad') on conflict(id) do nothing;
insert into public.event_activities (id,data,published,event_id,organizer_id) values ('expoferia-huayopata-2','{"id": "expoferia-huayopata-2", "eventId": "expoferia-huayopata", "name": "Pasacalles y expresión artística", "date": null, "time": null, "place": "Huyro", "description": "Componente descrito en el inventario turístico. Fecha, horario y realización de una próxima edición por confirmar.", "category": "Cultura", "organizerId": "municipalidad", "status": "Tradición documentada", "source": "https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=13024", "published": true}'::jsonb,true,'expoferia-huayopata','municipalidad') on conflict(id) do nothing;
insert into public.event_media (id,data,published,event_id) values ('wamanmarka-documental','{"id": "wamanmarka-documental", "eventId": "huamanmarca-raymi", "kind": "image", "url": "https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/calendar/wamanmarka.webp", "mobileUrl": "https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/calendar/wamanmarka-mobile.webp", "alt": "Sitio arqueológico de Wamanmarka en Huayopata, fotografiado en 2007", "represented": "Lugar de celebración: Wamanmarka. No muestra el Huamanmarca Raymi.", "author": "AgainErick", "source": "https://commons.wikimedia.org/wiki/File:Huamanmarka_Archaeological_site.jpg", "license": "CC BY-SA 3.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/", "authorization": "Reutilización permitida mediante licencia pública; atribución y compartir igual.", "transformation": "Redimensionado y convertido a WebP; sin alteración del contenido documental.", "year": 2007, "published": true}'::jsonb,true,'huamanmarca-raymi') on conflict(id) do nothing;
commit;
