// Run after BASE_PATH=/huayopata-viva/ npm run build.
// PLAYWRIGHT_MODULE and CHROMIUM_EXECUTABLE can point to an installed browser.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('fs'),http=require('http'),assert=require('assert/strict'),path=require('path');
const dir=process.cwd(),seed=JSON.parse(fs.readFileSync(dir+'/src/calendar/seed.json')),old=JSON.parse(fs.readFileSync(dir+'/supabase/seed-content.json'));
const server=http.createServer((req,res)=>{let f=dir+'/dist'+req.url.split('?')[0].replace('/huayopata-viva','');if(f.endsWith('/'))f+='index.html';if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f+='/index.html';if(!fs.existsSync(f)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.webp')?'image/webp':'text/html');res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(4176,'127.0.0.1',r));const b=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']});
for(const mobile of [false,true]){
 const p=await b.newPage({viewport:{width:mobile?390:1440,height:900},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 const tables={calendar_events:seed.events,event_activities:seed.activities,event_media:seed.media,event_organizers:seed.organizers,educational_institutions:seed.institutions};
 await p.route('**/rest/v1/**',r=>{const table=new URL(r.request().url()).pathname.split('/').pop();return r.fulfill({json:tables[table]?tables[table].map(data=>({data,updated_at:'2026-09-29T00:00:00Z'})):table==='places'?old.places:old.chapters})});
 await p.goto('http://127.0.0.1:4176/huayopata-viva/calendario/');await p.getByRole('heading',{level:1}).waitFor();assert.equal(await p.getByRole('button',{name:'Próximas fechas',exact:true}).getAttribute('aria-pressed'),'true');await p.getByLabel('Solo programas confirmados').check();await p.getByRole('heading',{name:'Aún no hay programas confirmados para esta selección'}).waitFor();await p.getByRole('button',{name:'Ver todas las fechas de referencia'}).click();assert.equal(await p.locator('.cal-pending .cal-card').count(),2);assert.equal(await p.locator('.cal-schools').getAttribute('open'),null);await p.getByRole('button',{name:'Mes',exact:true}).click();await p.getByLabel('Mes',{exact:true}).selectOption('5');await p.getByLabel('Año',{exact:true}).selectOption('2027');
 assert.match(await p.locator('.cal-month-announcement').innerText(),/junio de 2027/i);
 assert.match(await p.locator('.cal-day').nth(12).getAttribute('aria-label'),/Huamanmarca Raymi/);await p.locator('.cal-day').nth(12).click();assert.match(await p.locator('.cal-result-heading').innerText(),/En esta fecha/);assert.equal(await p.locator('.cal-shell>.cal-cards .cal-card').count(),1);assert.match(await p.locator('.cal-shell>.cal-cards').innerText(),/Huamanmarca Raymi/);
 await p.getByRole('button',{name:'Ver todo el mes'}).click();await p.getByLabel('Categoría',{exact:true}).selectOption('Educación');assert.equal(await p.locator('.cal-shell>.cal-cards .cal-card').count(),1);assert.match(await p.locator('.cal-shell>.cal-cards').innerText(),/Mariátegui/);
 await p.getByLabel('Localidad',{exact:true}).selectOption('Huyro');await p.getByLabel('Organizador',{exact:true}).selectOption('ie-0236380');assert.match(await p.locator('.cal-shell>.cal-cards').innerText(),/Mariátegui/);
 await p.getByRole('button',{name:'Próximas fechas',exact:true}).click();assert.equal(await p.locator('.cal-agenda-item').count(),1);await p.getByRole('button',{name:'Limpiar filtros'}).click();assert.ok(await p.locator('.cal-agenda-item').count()>10);await p.getByRole('button',{name:'Mes',exact:true}).click();assert.equal(await p.locator('.cal-school-grid a').count(),10);
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'calendar overflow');
 await p.locator('#calendar-content').scrollIntoViewIfNeeded();fs.mkdirSync(dir+'/test-results',{recursive:true});await p.screenshot({path:dir+'/test-results/calendar-'+(mobile?'mobile':'desktop')+'.png'});
 for(const e of seed.events){const response=await p.goto('http://127.0.0.1:4176/huayopata-viva/calendario/'+e.slug+'/',{waitUntil:'domcontentloaded'});assert.equal(response.status(),200);await p.getByRole('heading',{level:1,name:e.title}).waitFor();assert.match(await p.locator('#programa').innerText(),/Programa pendiente/);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,e.slug+' overflow');assert.ok(await p.locator('.cal-sources>a').count()>0);}
 await p.goto('http://127.0.0.1:4176/huayopata-viva/calendario/virgen-del-carmen/');const download=p.waitForEvent('download');await p.getByRole('button',{name:'Guardar fecha de referencia'}).click();assert.equal((await download).suggestedFilename(),'virgen-del-carmen.ics');
 await p.goto('http://127.0.0.1:4176/huayopata-viva/calendario/watunakuy/');assert.match(await p.locator('.cal-event-date').innerText(),/Fecha por confirmar/);assert.equal(await p.getByRole('button',{name:'Guardar fecha de referencia'}).count(),0);
 await p.goto('http://127.0.0.1:4176/huayopata-viva/calendario/');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.className),'cal-skip');await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.id),'calendar-content');assert.deepEqual(errors,[]);console.log('PASS calendar filters, monthly dates, agenda, 29 direct event routes, pending programs, download and keyboard',mobile?'mobile':'desktop');await p.close();
}
{const p=await b.newPage({viewport:{width:320,height:900},reducedMotion:'reduce'});const events=structuredClone(seed.events);const future=new Date().getFullYear()+1;events[0].status='Programa confirmado';events[0].editionYear=future;events[0].dateRule={kind:'one-off',start:future+'-06-19'};await p.route('**/rest/v1/**',r=>{const table=new URL(r.request().url()).pathname.split('/').pop();const rows={calendar_events:events,event_activities:seed.activities,event_media:seed.media,event_organizers:seed.organizers,educational_institutions:seed.institutions}[table];return rows?r.fulfill({json:rows.map(data=>({data,updated_at:"2026-10-01T00:00:00Z"}))}):r.abort()});await p.goto('http://127.0.0.1:4176/huayopata-viva/calendario/');await p.getByText('Contenido conectado a Supabase',{exact:false}).waitFor();await p.getByLabel('Solo programas confirmados').check();assert.equal(await p.locator('.cal-agenda-item').count(),1);assert.ok((await p.locator('.cal-agenda-item').innerText()).includes(events[0].title));assert.equal(await p.locator('.cal-month-nav').count(),0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);console.log('PASS confirmed-only positive fixture and 320px');await p.close()}
for(const scenario of ['offline','malformed']){const p=await b.newPage();await p.route('**/rest/v1/**',r=>scenario==='offline'?r.abort():r.fulfill({json:[{data:{id:'broken'}}]}));await p.goto('http://127.0.0.1:4176/huayopata-viva/calendario/');await p.getByText(/Respaldo local ·/).waitFor();assert.equal(await p.locator('.cal-school-grid a').count(),10);console.log('PASS bundled fallback',scenario);await p.close()}
await b.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
