import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,CalendarDays,MapPin,Flower2,GraduationCap,Leaf,Landmark,Music,Flag,Utensils,Trophy,Users,Download} from 'lucide-react';
import {sitePath} from '../lib/site';
import {useCalendar} from './data';
import {categories,dateKey,localityNames,occurrence,occursOn,datesInMonth,nextOccurrence,formatDate,dateLabel,editionStatus,type Event,type CalendarData,type Category,type Media} from './model';
import './calendar.css';
const icons={Cultura:Music,Religión:Flower2,Educación:GraduationCap,Institucional:Landmark,Producción:Leaf,Gastronomía:Utensils,Deportes:Trophy,Comunidad:Users};
const url=(slug='')=>sitePath('/calendario/'+(slug?slug+'/':''));
function Icon({category}:{category:Category}){const C=icons[category]||Flag;return <C size={30} aria-hidden="true"/>}
function Photo({media,hero=false}:{media:Media;hero?:boolean}){const [failed,setFailed]=useState(false);return failed?<div className="cal-photo-error">Fotografía no disponible · {media.represented}</div>:<picture><source media="(max-width: 650px)" srcSet={media.mobileUrl||media.url}/><img src={media.url} alt={media.alt} loading={hero?'eager':'lazy'} width="1600" height="1200" onError={()=>setFailed(true)}/></picture>}
function Art({event}:{event:Event}){return <div className={'cal-art cal-art-'+event.category} aria-label="Diseño editorial, fotografía local pendiente"><span className="cal-art-orbit"/><Icon category={event.category}/><span>{event.locality.split(' · ')[0]}</span><small>HUAYOPATA</small></div>}
function Card({event,data,date}:{event:Event;data:CalendarData;date?:Date|null}){const media=data.media.find(m=>m.eventId===event.id&&m.kind==='image');const d=date===undefined?nextOccurrence(event):date;return <a className="cal-card" href={url(event.slug)}><div className="cal-card-image">{media?<Photo media={media}/>:<Art event={event}/>}<span className="cal-category">{event.category}</span></div><div className="cal-card-copy"><span className="cal-card-date">{d?formatDate(d):'Fecha por confirmar'}</span><h3>{event.title}</h3><p><MapPin size={14} aria-hidden="true"/>{event.locality}</p><span className="cal-status">{editionStatus(event,d?.getFullYear()||new Date().getFullYear())}</span><small>Conocer la celebración <ArrowRight size={16}/></small></div></a>}
function Header(){return <header className="cal-nav"><a href={sitePath('/')}><img src={sitePath('assets/identity/escudo-huayopata.webp')} width="32" height="32" alt="Escudo de Huayopata"/> HUAYOPATA VIVA</a><nav aria-label="Navegación del calendario"><a href={url()}>Calendario</a><a href={sitePath('/#mapa')}>Mapa y servicios</a></nav></header>}
function Credit({media}:{media:Media}){return <p className="cal-credit">{media.represented} · <a href={media.source} target="_blank" rel="noreferrer">{media.author}, {media.year}</a> · <a href={media.licenseUrl} target="_blank" rel="noreferrer">{media.license}</a>. {media.transformation}</p>}
export function UpcomingCalendar(){const {data}=useCalendar();const upcoming=data.events.map(e=>({e,d:nextOccurrence(e)})).filter(x=>x.d&&!['Cancelado','Finalizado'].includes(editionStatus(x.e,x.d.getFullYear()))).sort((a,b)=>a.d!.getTime()-b.d!.getTime()).slice(0,3);return <section className="cal-upcoming" aria-labelledby="upcoming-title"><div className="cal-section-heading"><div><p className="cal-eyebrow">HUAYOPATA CELEBRA</p><h2 id="upcoming-title">Próximamente en Huayopata</h2><p>Fechas tradicionales documentadas. Consulta la ficha para conocer el estado de cada programa.</p></div><a className="cal-button" href={url()}>Ver calendario completo <ArrowRight size={18}/></a></div><div className="cal-cards">{upcoming.map(({e,d})=><Card key={e.id} event={e} data={data} date={d}/>)}</div></section>}
export default function Calendar({slug}:{slug?:string}){
 const {data,status}=useCalendar();const event=slug?data.events.find(e=>e.slug===slug):undefined;
 useEffect(()=>{document.title=(event?.title||'Huayopata celebra · Calendario vivo')+' | Huayopata Viva'},[event]);
 return <div className="cal-site"><a className="cal-skip" href="#calendar-content">Ir al contenido</a><Header/>{slug?(event?<EventPage event={event} data={data}/>:<main tabIndex={-1} id="calendar-content" className="cal-shell"><h1>Celebración no encontrada</h1><a href={url()}>Volver al calendario</a></main>):<CalendarPage data={data}/>}<footer className="cal-footer"><strong>Un archivo vivo, una memoria compartida.</strong><p>{status==='live'?'Contenido conectado a Supabase':status==='loading'?'Consultando actualizaciones · información local disponible':'Respaldo local · no se pudieron consultar las últimas actualizaciones'}. Las fechas tradicionales no confirman un programa anual.</p><a href={sitePath('/')}>Volver a Huayopata Viva</a></footer></div>
}
function CalendarPage({data}:{data:CalendarData}){
 const today=new Date();const [cursor,setCursor]=useState(()=>new Date(today.getFullYear(),today.getMonth(),1,12));const [category,setCategory]=useState('');const [locality,setLocality]=useState('');const [organizer,setOrganizer]=useState('');const [view,setView]=useState<'month'|'agenda'>('month');const [selected,setSelected]=useState<string|null>(null);
 const year=cursor.getFullYear(),month=cursor.getMonth();
 const filtered=useMemo(()=>data.events.filter(e=>(!category||e.category===category)&&(!locality||localityNames(e).includes(locality))&&(!organizer||e.organizerId===organizer)),[data,category,locality,organizer]);
 const dated=filtered.map(e=>({e,d:datesInMonth(e,year,month)[0]||null})).filter(x=>x.d).sort((a,b)=>a.d!.getTime()-b.d!.getTime());
 const undated=filtered.filter(e=>e.dateRule.kind==='unknown');
 const first=(new Date(year,month,1).getDay()+6)%7;const days=new Date(year,month+1,0).getDate();
 const upcoming=filtered.map(e=>({e,d:nextOccurrence(e)})).filter(x=>x.d).sort((a,b)=>a.d!.getTime()-b.d!.getTime());
 const selectedEvents=selected?dated.filter(x=>occursOn(x.e,new Date(selected+'T12:00:00'))):dated;
 const move=(step:number)=>{setCursor(new Date(year,month+step,1,12));setSelected(null)};
 const reset=()=>{setCategory('');setLocality('');setOrganizer('');setSelected(null)};
 const hero=data.media.find(m=>m.id==='wamanmarka-documental');
 return <><section className="cal-hero">{hero&&<Photo media={hero} hero/>}<div className="cal-hero-shade"/><div className="cal-hero-copy"><p className="cal-eyebrow">HUAYOPATA CELEBRA · CALENDARIO VIVO</p><h1>Un valle.<br/><em>Muchas formas<br/>de encontrarnos.</em></h1><p>Celebraciones, escuelas y comunidades. Descubre lo que da vida al distrito y vuelve a su memoria.</p><a className="cal-button cal-button-light" href="#calendar-content">Explorar el calendario <CalendarDays size={18}/></a></div><span className="cal-hero-place"><MapPin size={16}/> Wamanmarka · Huayopata</span></section>{hero&&<Credit media={hero}/>}
 <main tabIndex={-1} id="calendar-content" className="cal-shell"><div className="cal-section-heading"><div><p className="cal-eyebrow">EL RITMO DEL VALLE</p><h2>Encuentra tu próximo encuentro.</h2></div><p className="cal-editor-note">Una fecha tradicional es una referencia cultural. Los programas pendientes se confirman con los responsables de cada edición.</p></div>
 <div className="cal-filters"><label>Categoría<select aria-label="Categoría" value={category} onChange={e=>{setCategory(e.target.value);setSelected(null)}}><option value="">Todas las categorías</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Localidad<select aria-label="Localidad" value={locality} onChange={e=>{setLocality(e.target.value);setSelected(null)}}><option value="">Todo el distrito</option>{[...new Set(data.events.flatMap(localityNames))].sort().map(l=><option key={l}>{l}</option>)}</select></label><label>Organizador<select aria-label="Organizador" value={organizer} onChange={e=>{setOrganizer(e.target.value);setSelected(null)}}><option value="">Todos los organizadores</option>{data.organizers.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><button className="cal-reset" onClick={reset}>Limpiar filtros</button></div>
 <div className="cal-toolbar"><div className="cal-view" role="group" aria-label="Vista del calendario"><button aria-pressed={view==='month'} onClick={()=>setView('month')}>Mes</button><button aria-pressed={view==='agenda'} onClick={()=>setView('agenda')}>Próximas fechas</button></div><div className="cal-month-nav"><button aria-label="Mes anterior" onClick={()=>move(-1)}><ArrowLeft size={20}/></button><label><span className="cal-sr">Mes</span><select aria-label="Mes" value={month} onChange={e=>{setCursor(new Date(year,Number(e.target.value),1,12));setSelected(null)}}>{Array.from({length:12},(_,m)=><option key={m} value={m}>{new Date(2026,m,1).toLocaleDateString('es-PE',{month:'long'})}</option>)}</select></label><label><span className="cal-sr">Año</span><select aria-label="Año" value={year} onChange={e=>{setCursor(new Date(Number(e.target.value),month,1,12));setSelected(null)}}>{Array.from({length:201},(_,i)=>1900+i).map(y=><option value={y} key={y}>{y}</option>)}</select></label><button aria-label="Mes siguiente" onClick={()=>move(1)}><ArrowRight size={20}/></button><button onClick={()=>{setCursor(new Date(today.getFullYear(),today.getMonth(),1,12));setSelected(null)}}>Hoy</button></div></div>
 {view==='month'?<><p className="cal-month-announcement" aria-live="polite">{cursor.toLocaleDateString('es-PE',{month:'long',year:'numeric'})} · {dated.length} referencias culturales o educativas</p><div className="cal-weekdays" aria-hidden="true">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=><span key={d}>{d}</span>)}</div><div className="cal-month-grid" aria-label="Días del mes">{Array.from({length:first},(_,i)=><div className="cal-day-empty" key={'empty'+i}/>)}{Array.from({length:days},(_,i)=>{const day=i+1;const key=dateKey(new Date(year,month,day));const matches=dated.filter(x=>occursOn(x.e,new Date(key+'T12:00:00')));const current=key===dateKey(today);return <button key={day} className={'cal-day'+(selected===key?' cal-day-selected':'')} aria-current={current?'date':undefined} aria-pressed={selected===key} aria-label={`${day} de ${cursor.toLocaleDateString('es-PE',{month:'long'})}, ${matches.length} eventos${matches.length?': '+matches.map(x=>x.e.title).join(', '):''}`} onClick={()=>setSelected(selected===key?null:key)}><span className="cal-day-number">{day}</span><div className="cal-day-labels">{matches.slice(0,2).map(x=><span key={x.e.id}>{x.e.title}</span>)}{matches.length>2&&<small>+{matches.length-2} más</small>}</div>{matches.length>0&&<span className="cal-day-dots" aria-hidden="true">{matches.slice(0,3).map(x=><i key={x.e.id} className={'cal-dot cal-dot-'+x.e.category}/>)}</span>}</button>})}{Array.from({length:(7-(first+days)%7)%7},(_,i)=><div className="cal-day-empty" key={"tail"+i}/>)}</div><div className="cal-result-heading"><h3>{selected?'En esta fecha':'En este mes'}</h3>{selected&&<button onClick={()=>setSelected(null)}>Ver todo el mes</button>}</div><div className="cal-cards" aria-live="polite">{selectedEvents.length?selectedEvents.map(({e,d})=><Card key={e.id} event={e} data={data} date={d}/>):<p className="cal-empty">No hay actividades documentadas para esta selección. Prueba otra fecha o consulta las fichas pendientes.</p>}</div></>:<div className="cal-agenda" aria-live="polite">{upcoming.length?upcoming.map(({e,d})=><a href={url(e.slug)} className="cal-agenda-item" key={e.id}><span className="cal-agenda-date">{formatDate(d!)}</span><Icon category={e.category}/><span><strong>{e.title}</strong><small>{e.locality} · {editionStatus(e,d!.getFullYear())}</small></span><ArrowRight size={18}/></a>):<p>No hay próximas fechas con estos filtros.</p>}</div>}
 <section className="cal-pending"><div className="cal-section-heading"><div><p className="cal-eyebrow">POR ESCUCHAR A LA COMUNIDAD</p><h2>Fecha por confirmar</h2><p>Estas fichas se mantienen visibles hasta que exista una fecha documentada.</p></div></div><div className="cal-cards">{undated.length?undated.map(e=><Card key={e.id} event={e} data={data} date={null}/>):<p>No hay fichas pendientes para estos filtros.</p>}</div></section>
 <section className="cal-schools"><p className="cal-eyebrow">LAS ESCUELAS TAMBIÉN CELEBRAN</p><h2>Educación con identidad local.</h2><p>Diez instituciones identificadas documentalmente. Un aniversario tiene referencia documentada; nueve fechas y los programas necesitan validación de cada dirección.</p><div className="cal-school-grid">{data.institutions.filter(i=>!locality||i.locality===locality).map(i=><a key={i.id} href={url('aniversario-'+i.id)}><GraduationCap size={22}/><strong>{i.name}</strong><span>{i.locality} · {i.level}</span><small>Código modular: {i.modularCode}<br/>{i.anniversaryStatus}</small></a>)}</div></section>
 </main></>
}
function downloadDate(event:Event,date:Date){
 const escape=(v:string)=>v.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
 const next=event.dateRule.kind==='one-off'&&event.dateRule.end?new Date(event.dateRule.end+'T12:00:00'):new Date(date);next.setDate(next.getDate()+1);const compact=(d:Date)=>dateKey(d).replace(/-/g,'');
 const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Huayopata Viva//Calendario vivo//ES','BEGIN:VEVENT',`UID:${event.id}-${date.getFullYear()}@huayopata-viva`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;VALUE=DATE:${compact(date)}`,`DTEND;VALUE=DATE:${compact(next)}`,`SUMMARY:${escape(event.title+' · referencia tradicional')}`,`LOCATION:${escape(event.locality)}`,`DESCRIPTION:${escape(event.editorialNote)}`,editionStatus(event,date.getFullYear())==='Programa confirmado'?'STATUS:CONFIRMED':'STATUS:TENTATIVE','END:VEVENT','END:VCALENDAR'];
 const blob=new Blob([lines.join('\r\n')+'\r\n'],{type:'text/calendar;charset=utf-8'});const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=event.slug+'.ics';a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);
}
function EventPage({event,data}:{event:Event;data:CalendarData}){
 const d=nextOccurrence(event);const [year,setYear]=useState(d?.getFullYear()||new Date().getFullYear());const date=occurrence(event,year);const organizer=data.organizers.find(o=>o.id===event.organizerId);const media=data.media.filter(m=>m.eventId===event.id);const image=media.find(m=>m.kind==='image');const institution=data.institutions.find(i=>i.id===event.institutionId);const components=data.activities.filter(a=>a.eventId===event.id&&a.status==='Tradición documentada');const annual=data.activities.filter(a=>a.eventId===event.id&&a.status!=='Tradición documentada'&&a.date?.startsWith(String(year)));
 return <main tabIndex={-1} id="calendar-content"><div className="cal-event-hero">{image?<Photo media={image} hero/>:<Art event={event}/>}<div className="cal-event-shade"/><div className="cal-event-heading"><a href={url()}><ArrowLeft size={16}/> Todas las celebraciones</a><p className="cal-eyebrow">{event.category} · {event.locality}</p><h1>{event.title}</h1><p className="cal-event-date">{dateLabel(event,year)}</p><span className="cal-status">{editionStatus(event,year)}</span></div></div>{image&&<Credit media={image}/>}
 <div className="cal-shell cal-event-body"><div className="cal-event-main"><p className="cal-eyebrow">MEMORIA Y SIGNIFICADO</p><h2>Un encuentro con nuestra historia.</h2><p className="cal-lead">{event.history}</p><div className="cal-notice"><strong>{event.dateRule.kind==='unknown'?'Fecha por confirmar':'Referencia cultural · consulta el programa'}</strong><p>{event.editorialNote}</p></div>
 <section id="programa"><div className="cal-section-heading"><div><p className="cal-eyebrow">CADA EDICIÓN TIENE SU PROPIA HISTORIA</p><h2>Programa de {year}</h2></div><label>Consultar año<select aria-label="Año del programa" value={year} onChange={e=>setYear(Number(e.target.value))}>{Array.from({length:9},(_,i)=>new Date().getFullYear()-4+i).map(y=><option key={y}>{y}</option>)}</select></label></div>{annual.length?<div className="cal-activities">{annual.map(a=><article key={a.id}><span className="cal-status">{a.status}</span><h3>{a.name}</h3><p>{a.date} · {a.time||'Hora por confirmar'} · {a.place}</p><p>{a.description}</p><small>{a.category} · {data.organizers.find(o=>o.id===a.organizerId)?.name||'Organizador por confirmar'}</small><a href={a.source}>Fuente del programa ↗</a></article>)}</div>:<div className="cal-program-pending"><CalendarDays size={30}/><h3>Programa pendiente</h3><p>Sin actividades confirmadas para {year}. Aquí se publicarán las fechas, horarios, lugares y responsables cuando exista una fuente oficial.</p></div>}</section>
 {components.length>0&&<section className="cal-documentary"><h2>Lo que documenta el inventario</h2><p>Componentes culturales registrados; no son el programa de {year}.</p>{components.map(a=><details key={a.id}><summary>{a.name}</summary><p>{a.description}</p><p>Lugar de referencia: {a.place}. Fecha y hora: por confirmar.</p><p>{a.category} · {data.organizers.find(o=>o.id===a.organizerId)?.name} · {a.status}</p><a href={a.source} target="_blank" rel="noreferrer">Leer la ficha institucional ↗</a></details>)}</section>}
 {institution&&<section><h2>La institución</h2><dl className="cal-facts"><div><dt>Nombre</dt><dd>{institution.name}</dd></div><div><dt>Código modular</dt><dd>{institution.modularCode}</dd></div><div><dt>Nivel y localidad</dt><dd>{institution.level} · {institution.locality}</dd></div><div><dt>Aniversario</dt><dd>{institution.anniversaryStatus}</dd></div></dl><p>{institution.note}</p></section>}
 <section><h2>Archivo de ediciones anteriores</h2>{event.editions.length?event.editions.map(e=><article className="cal-archive" key={e.year}><h3>{e.year} · Finalizado</h3><p>{e.description}</p><a href={e.source}>Consultar fuente ↗</a></article>):<p>Sin programas de ediciones anteriores incorporados todavía.</p>}{event.photoPending&&<p className="cal-photo-pending">Fotografías y videos auténticos de la celebración: pendientes de documentación y autorización. {image?'La imagen disponible corresponde al lugar, no a una edición del evento.':''}</p>}{media.filter(m=>m.kind==='video').map(m=><figure key={m.id}><video controls preload="none" src={m.url}/><figcaption>{m.represented} · {m.author} · {m.license}</figcaption></figure>)}</section>
 <section className="cal-sources"><h2>Fuentes y revisión</h2><p>Revisión documental: {event.updatedAt}. Una fuente histórica no confirma una próxima convocatoria.</p>{event.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer"><strong>{s.label}</strong><span>{s.kind} · consultada el {s.accessedAt} ↗</span></a>)}{media.map(m=><details key={m.id}><summary>Procedencia y derechos de imagen</summary><p>{m.represented}</p><p>Autor: {m.author}. {m.authorization}</p><Credit media={m}/></details>)}</section>
 </div><aside className="cal-event-aside"><div className="cal-info-card"><Icon category={event.category}/><h3>Prepara tu visita</h3><dl><dt>Fecha</dt><dd>{dateLabel(event,year)}</dd><dt>Localidad</dt><dd>{event.locality}</dd><dt>Organización</dt><dd>{organizer?.name||'Por confirmar'}</dd></dl>{organizer?.url&&<a href={organizer.url} target="_blank" rel="noreferrer">Consultar al organizador ↗</a>}{date&&<button className="cal-button" onClick={()=>downloadDate(event,date)}><Download size={17}/> Guardar fecha de referencia</button>}<p>Confirma accesos y horarios antes de salir. Pide permiso para fotografiar personas y respeta los espacios ceremoniales.</p></div>
 <div className="cal-info-card"><MapPin size={24}/><h3>En el territorio</h3>{event.location?<><iframe title="Mapa de referencia de Wamanmarka" loading="lazy" src={`https://www.openstreetmap.org/export/embed.html?bbox=${event.location.lng-.008}%2C${event.location.lat-.006}%2C${event.location.lng+.008}%2C${event.location.lat+.006}&layer=mapnik&marker=${event.location.lat}%2C${event.location.lng}`}/><p>{event.location.label}</p><a href={event.location.source}>Fuente de la referencia ↗</a></>:<p>Referencia de localidad: {event.locality}. Escenario exacto y coordenadas por confirmar; no se muestra un punto inventado.</p>}<a className="cal-button" href={sitePath('/#mapa')}>Abrir mapa y servicios <ArrowRight size={17}/></a><a href={sitePath('/descubre/'+event.relatedTopic+'/')}>{event.relatedTopic==='wamanmarka'?'Conocer Wamanmarka':'Conocer las comunidades'} ↗</a><a href={sitePath('/descubre/cafe/')}>Mundo cafetalero ↗</a><a href={sitePath('/descubre/te/')}>Mundo del té ↗</a></div></aside></div>
 </main>
}
