import {useRef,useState} from 'react';
import {Expand,X} from 'lucide-react';
import {sitePath} from './lib/site';
import './biodiversity.css';
const photos={
 cinclodes:{name:'Churrete real',species:'Cinclodes aricomae',author:'Jon Irvine',date:'7 de septiembre de 2018',license:'CC BY-SA 2.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/2.0/',source:'https://commons.wikimedia.org/wiki/File:Cinclodes_aricomae_-_Royal_Cinclodes;_Abra_Malaga,_Cuzco,_Peru.jpg',alt:'Ave de plumaje gris y pardo sobre suelo cubierto de musgo en Abra Málaga',width:1280,height:853},
 ourisia:{name:'Flores de altura',species:'Ourisia chamaedrifolia',author:'Ruth Gutiérrez Oliveros',date:'30 de octubre de 2022',license:'CC0 1.0',licenseUrl:'https://creativecommons.org/publicdomain/zero/1.0/',source:'https://commons.wikimedia.org/wiki/File:Ourisia_chamaedrifolia_-_Ruth_Guti%C3%A9rrez_Oliveros_-_243470335.jpeg',alt:'Flores rojas tubulares de Ourisia chamaedrifolia entre hojas verdes y rocas en Abra Málaga',width:1280,height:960},
 cranioleuca:{name:'Un registro de Abra Málaga',species:'Cranioleuca marcapatae',author:'Nick Athanas',date:'12 de marzo de 2012',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',source:'https://commons.wikimedia.org/wiki/File:Cranioleuca_marcapatae_-_Marcapata_Spinetail_(nominate_ssp.).jpg',alt:'Ave de cabeza castaña y cola rojiza posada entre tallos de bambú en Abra Málaga',width:1280,height:886}
};
export function WildlifePhoto({id}:{id:keyof typeof photos}){
 const p=photos[id],dialog=useRef<HTMLDialogElement>(null),[failed,setFailed]=useState(false);
 const src=(size:number)=>sitePath(`/assets/biodiversity/${id}-${size}.webp`);
 return <figure className="hv-wildlife-photo">
 {failed?<div className="hv-wildlife-fallback">Fotografía no disponible. Consulta el registro original en los créditos.</div>:<button className="hv-wildlife-open" onClick={()=>dialog.current?.showModal()} aria-label={`Ampliar fotografía: ${p.species}`}><img src={src(1280)} srcSet={`${src(640)} 640w, ${src(1280)} 1280w`} sizes="(max-width: 700px) 92vw, 48vw" width={p.width} height={p.height} loading="lazy" decoding="async" alt={p.alt} onError={()=>setFailed(true)}/><span><Expand size={18} aria-hidden="true"/> Ampliar</span></button>}
 <figcaption><span className="hv-wildlife-place">ABRA MÁLAGA · REGISTRO FOTOGRÁFICO</span><strong>{p.name}</strong><i>{p.species}</i><details><summary>Fotografía y procedencia</summary><p>{p.author} · {p.date}. Lugar indicado por la fuente: Abra Málaga, Cusco, Perú.</p><p><a href={p.source} target="_blank" rel="noreferrer">Ver registro original ↗</a> · <a href={p.licenseUrl} target="_blank" rel="noreferrer">{p.license}</a></p><p>Adaptación web: reducción de tamaño y conversión a WebP; sin modificación del contenido.</p></details></figcaption>
 <dialog ref={dialog} className="hv-wildlife-dialog" aria-label={`Fotografía de ${p.species}`}><button autoFocus onClick={()=>dialog.current?.close()} aria-label="Cerrar fotografía"><X/></button><img loading="lazy" decoding="async" src={src(1280)} alt={p.alt} width={p.width} height={p.height}/><p><i>{p.species}</i> · Abra Málaga<br/>{p.author} · {p.license}</p></dialog>
 </figure>
}
export default function Biodiversity(){return <section className="hv-biodiversity" id="biodiversidad" aria-labelledby="biodiversity-title"><header><span>FLORA Y FAUNA · ABRA MÁLAGA</span><h2 id="biodiversity-title">Observar de cerca.<br/><em>Mantener la distancia.</em></h2><p>Dos registros fotográficos del paso de Abra Málaga. Cada imagen conserva su lugar, fecha y autor; no representa un avistamiento garantizado durante la visita.</p></header><div className="hv-biodiversity-grid"><WildlifePhoto id="cinclodes"/><WildlifePhoto id="ourisia"/></div><p className="hv-biodiversity-note">Observa desde los senderos autorizados. No recolectes plantas ni alimentes aves. Confirma el acceso con responsables locales antes de salir.</p></section>}
