import {useRef,useState} from 'react';
import {Expand,X} from 'lucide-react';
import {sitePath} from './lib/site';
import './chapter-complement.css';
const records={
 wamanmarka:{asset:'wamanmarka-archivo',label:'PATRIMONIO · ARCHIVO MUNICIPAL',title:'Los muros, en detalle.',place:'Wamanmarka · Huayopata',alt:'Acceso entre muros de piedra de Wamanmarka, con el rótulo original de la fotografía municipal',author:'Munihuayopata',date:'Publicada el 21 de septiembre de 2015; EXIF del 7 de mayo de 2014.',source:'https://commons.wikimedia.org/wiki/File:HUAMANMARCA.jpg',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',intro:'La fotografía permite observar las juntas entre las piedras, los bloques del acceso y los muros del fondo.',points:[['Mira los detalles','Compara el tamaño y la disposición de las piedras que aparecen en esta vista.'],['Distingue imagen y recorrido','Es un registro de archivo, no un plano ni una indicación del acceso habilitado actualmente.']],note:'Se conserva el rótulo de la imagen original.'},
 comunidades:{asset:'huyro-plaza',label:'VIDA LOCAL · MEMORIA FOTOGRÁFICA',title:'La plaza de Huyro, en el archivo.',place:'Plaza de Huyro · Huayopata',alt:'Vista histórica de la plaza de Huyro, con monumento central, edificios y laderas al fondo',author:'fyal',date:'EXIF del 14 de septiembre de 2010; publicada el 11 de noviembre de 2011.',source:'https://commons.wikimedia.org/wiki/File:Huyro.jpg',license:'CC0 1.0',licenseUrl:'https://creativecommons.org/publicdomain/zero/1.0/',intro:'Una vista de la plaza permite reconocer la relación entre el espacio urbano y las laderas que rodean Huyro.',points:[['Observa el lugar','El monumento, los edificios y las montañas forman parte de este registro fotográfico.'],['Consulta la actividad actual','La imagen no documenta una festividad ni acredita el estado actual de la plaza. Las celebraciones tienen sus propias fechas y programas.']],note:'Fotografía histórica. Fecha de captura indicada por los metadatos del archivo.'}
};
export default function ChapterComplement({tema}:{tema:keyof typeof records}){
 const p=records[tema],modal=useRef<HTMLDialogElement>(null),[failed,setFailed]=useState(false);
 const src=(width:number)=>sitePath(`assets/chapters/${p.asset}-${width}.webp`);
 return <section className="hv-chapter-complement" aria-labelledby={`archive-${tema}`}>
 <div className="hv-chapter-complement-copy"><span>{p.label}</span><h2 id={`archive-${tema}`}>{p.title}</h2><p>{p.intro}</p><dl>{p.points.map(([title,body])=><div key={title}><dt>{title}</dt><dd>{body}</dd></div>)}</dl></div>
 <figure><button className="hv-chapter-photo" aria-label={`Ampliar fotografía: ${p.place}`} onClick={()=>modal.current?.showModal()} disabled={failed}>{failed?<span>Fotografía no disponible. Puedes consultar la fuente al pie.</span>:<><img src={src(1280)} srcSet={`${src(640)} 640w, ${src(1280)} 1280w`} sizes="(max-width: 760px) 92vw, 58vw" width="1280" height="960" alt={p.alt} loading="lazy" decoding="async" onError={()=>setFailed(true)}/><span><Expand size={18} aria-hidden="true"/> Ampliar</span></>}</button><figcaption><strong>{p.place}</strong><small>{p.author} · {p.license}</small><details><summary>Fecha, fuente y licencia</summary><p>{p.date} {p.note}</p><p><a href={p.source} target="_blank" rel="noreferrer">Registro original ↗</a> · <a href={p.licenseUrl} target="_blank" rel="noreferrer">{p.license}</a></p><p>Redimensionado y convertido a WebP, sin alterar encuadre ni contenido. Se conserva la licencia del original.</p></details></figcaption></figure>
 <dialog className="hv-chapter-modal" ref={modal} aria-label={`Fotografía: ${p.place}`}><button autoFocus aria-label="Cerrar fotografía" onClick={()=>modal.current?.close()}><X/></button><img src={src(1280)} alt={p.alt} loading="lazy" decoding="async" width="1280" height="960"/><p>{p.place} · {p.author} · {p.license}</p></dialog>
 </section>
}
