import {UpcomingCalendar} from './calendar/Calendar';
import './community-transition.css';
import BotanicalTrace from './BotanicalTrace';
import ChapterComplement from './ChapterComplement';
import Biodiversity, {WildlifePhoto} from './Biodiversity';
import GuideDocumentary from './GuideDocumentary';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Mountain,Bird,Waves,Bike,Leaf,Coffee,Sprout,Flame,Droplets,Sun,Users,Utensils,Camera,Play,Pause} from 'lucide-react';
import {sitePath} from './lib/site';
const media='https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/';
export function useEditorialReveal(key?:string){
 useEffect(()=>{
  if(!('IntersectionObserver' in window)||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-revealed');observer.unobserve(e.target)}}),{threshold:.08});
  document.querySelectorAll('[data-reveal]').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el)});
  return()=>{observer.disconnect();document.querySelectorAll('.reveal-ready').forEach(el=>el.classList.remove('reveal-ready'))};
 },[key]);
}
const nature=[
 {icon:Mountain,label:'BOSQUE Y ALTURA',title:'Vegetación de Abra Málaga.',body:'Abra Málaga reúne pajonales, bosques de queuña y bosque de neblina. El área de conservación requiere permiso previo para ingresar.',url:'https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=3700'},
 {icon:Bird,label:'OBSERVACIÓN DE AVES',title:'Aves registradas en Abra Málaga.',body:'La conservación de Abra Málaga protege aves como el churrete real. Observa con guía, a distancia y sin reproducir sonidos para atraerlas.',url:'https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=3700'},
 {icon:Waves,label:'AGUA Y CAMINATAS',title:'Cascada de Pasto Grande.',body:'En el sector Pasto Grande, cerca de San Pablo, el inventario turístico registra una cascada rodeada de vegetación. Consulta el sendero y el caudal con un guía local.',url:'https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=12460'},
 {icon:Bike,label:'AVENTURA RESPONSABLE',title:'Ciclismo desde Abra Málaga.',body:'El inventario de Abra Málaga incluye ciclismo. Coordina equipo, guía y transporte; confirma la carretera y el clima antes de iniciar el descenso.',url:'https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=3700'},
];
export function NatureSection(){return <section className="hv-nature" id="naturaleza" aria-labelledby="nature-title"><div className="hv-nature-heading" data-reveal><span>NATURALEZA Y ACCESOS</span><h2 id="nature-title">Bosques, aves<br/>y cascadas.</h2><p>Consulta los recursos registrados en el inventario turístico y confirma sus condiciones de acceso.</p></div><div className="hv-nature-grid">{nature.map(n=><article key={n.label} data-reveal><n.icon size={34} strokeWidth={1.4}/><span>{n.label}</span><h3>{n.title}</h3><p>{n.body}</p><a href={n.url} target="_blank" rel="noreferrer">Consultar ficha MINCETUR <ArrowUpRight size={17}/></a></article>)}</div></section>}

const teaSteps=[{icon:Sprout,title:'Cultivo',body:'Primero, mira la planta. Pregunta cómo se cuida el suelo y qué hojas se seleccionan durante la cosecha.'},{icon:Leaf,title:'Cosecha',body:'La selección de las hojas tiernas es parte del oficio. Observa el trabajo con permiso y evita tocar o arrancar hojas.'},{icon:Flame,title:'Elaboración',body:'Marchitado, oxidación y secado son procesos que pueden variar según el tipo de té. Pide al productor que te explique su método.'},{icon:Droplets,title:'Degustación',body:'Compara aroma, color y sabor. Pregunta por la cantidad de hojas, la temperatura del agua y el tiempo de infusión.'}];
const coffeeSteps=[{icon:Sprout,title:'Cafetal',body:'Consulta la variedad cultivada, el manejo de sombra y las labores de mantenimiento de la parcela.'},{icon:Coffee,title:'Cereza',body:'El café es un fruto. La selección de cerezas maduras influye en la calidad que llegará a la taza.'},{icon:Droplets,title:'Beneficio',body:'Cada productor elige su proceso: pregunta por despulpado, fermentación o secado del fruto entero, sin dar por hecho un único método.'},{icon:Sun,title:'Secado',body:'El secado y el almacenamiento ayudan a conservar el grano. Consulta cómo se controla la humedad en la finca.'},{icon:Flame,title:'Tostado',body:'El tueste desarrolla los aromas del café. Pregunta cómo el perfil de tostado cambia la bebida.'},{icon:Coffee,title:'La taza',body:'Consulta el origen del lote y las condiciones de preparación durante la degustación.'}];
function ProcessExplorer({coffee=false}:{coffee?:boolean}){
 const [index,setIndex]=useState(0);const steps=coffee?coffeeSteps:teaSteps;const step=steps[index];
 return <section className={'hv-process-explorer '+(coffee?'is-coffee':'is-tea')} id="experiencias"><div className="hv-editorial-heading"><div className="hv-process-intro"><span>{coffee?'ETAPAS DEL CAFÉ':'ETAPAS DEL TÉ'}</span><h2>{coffee?'Cosecha y procesamiento del café.':'Cultivo y elaboración del té.'}</h2><p>Elige una etapa para descubrir qué observar y qué preguntar durante una visita.</p></div><BotanicalTrace kind={coffee?'cafe':'te'}/></div><div className="hv-process-layout" data-reveal><GuideDocumentary tema={coffee?'cafe':'te'}/><div className="hv-process-panel"><div className="hv-process-tabs" role="tablist" aria-label={coffee?'Etapas del café':'Etapas del té'}>{steps.map((s,i)=><button key={s.title} id={'stage-tab-'+i} role="tab" aria-selected={index===i} aria-controls="stage-panel" tabIndex={index===i?0:-1} onClick={()=>setIndex(i)} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?steps.length-1:(index+(e.key==='ArrowRight'?1:-1)+steps.length)%steps.length;setIndex(next);document.getElementById('stage-tab-'+next)?.focus()}}}><s.icon size={18}/>{s.title}</button>)}</div><article role="tabpanel" id="stage-panel" aria-labelledby={'stage-tab-'+index} key={index}><span>0{index+1} / 0{steps.length}</span><step.icon size={50} strokeWidth={1.1}/><h3>{step.title}</h3><p>{step.body}</p><button className="hv-process-next" onClick={()=>setIndex((index+1)%steps.length)}>Siguiente etapa <ArrowUpRight size={18}/></button></article></div></div></section>
}
function Landscape(){return <><section className="hv-altitude" id="experiencias"><div data-reveal><span>DEL AIRE FRÍO AL BOSQUE HÚMEDO</span><h2>Ambientes<br/><em>de Abra Málaga.</em></h2><p>El área de conservación de Abra Málaga se extiende entre 2.200 y 4.400 metros de altitud, según MINCETUR.</p><a href="https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=3700" target="_blank" rel="noreferrer">Conocer el área de conservación ↗</a></div><ol data-reveal><li><Mountain/><strong>Pajonal y queuña</strong><p>En la parte alta, observa el paisaje andino y los relictos de bosque de Polylepis.</p></li><li><Leaf/><strong>Zona de transición</strong><p>Bosques enanos y bofedales conectan ambientes diferentes.</p></li><li><Droplets/><strong>Bosque de neblina</strong><p>La vegetación se hace más densa. Consulta las condiciones del acceso antes de iniciar la caminata.</p></li></ol></section><Biodiversity/><NatureSection/></>}
function Heritage(){const [active,setActive]=useState(0);const details=[{title:'Recintos',body:'El inventario oficial describe recintos organizados alrededor de un patio. Observa la disposición de los espacios sin subir a los muros.'},{title:'Patio',body:'El patio ayuda a leer cómo se relacionan los recintos. Una guía local puede aportar contexto a lo que ves.'},{title:'Ushnu',body:'MINCETUR registra un ushnu en el conjunto. Consulta su interpretación con una guía y respeta las áreas delimitadas.'}];return <section className="hv-heritage-explore" id="experiencias"><div className="hv-editorial-heading" data-reveal><span>ELEMENTOS DEL CONJUNTO</span><h2>Arquitectura<br/>de Wamanmarka.</h2><p>Explora tres elementos descritos en el inventario oficial. La fotografía de archivo permite observar la construcción; no es un plano del sitio.</p></div><ChapterComplement tema="wamanmarka"/><div className="hv-heritage-reading" data-reveal><div aria-label="Elementos del conjunto">{details.map((d,i)=><button key={d.title} aria-pressed={active===i} onClick={()=>setActive(i)}><span>0{i+1}</span>{d.title}<ArrowUpRight size={18}/></button>)}</div><article aria-live="polite"><h3>{details[active].title}</h3><p>{details[active].body}</p><small>No es un plano arqueológico ni una ruta de acceso.</small></article></div></section>}
function ValleyActivities(){return <section className="hv-valley-experiences" aria-labelledby="valley-activities-title"><div className="hv-editorial-heading" data-reveal><span>AVENTURA Y NATURALEZA</span><h2 id="valley-activities-title">Ciclismo y observación<br/>de aves.</h2><p>Dos experiencias para conocer el paisaje con preparación, acompañamiento y respeto.</p></div><div className="hv-valley-experience-grid"><article id="ciclismo" data-reveal><Bike size={34} aria-hidden="true"/><span>01 · INCA JUNGLE</span><h3>Descenso en bicicleta.</h3><p>El descenso desde Abra Málaga hacia la ceja de selva forma parte de las propuestas de mountain bike del Inca Jungle, una alternativa de viaje hacia Machu Picchu. El recorrido debe coordinarse con un operador y adaptarse a las condiciones del día.</p><details><summary>Qué confirmar antes de pedalear <ArrowUpRight size={18} aria-hidden="true"/></summary><ul><li>Operador, guía, equipo de protección y estado de la bicicleta.</li><li>Condiciones de la carretera, clima, punto de inicio y recogida.</li><li>Nivel requerido, asistencia y plan de respuesta del operador.</li></ul><a href="https://www.peru.travel/es/inspirate/cuales-son-las-mejores-rutas-de-trekking-para-llegar-a-machupicchu" target="_blank" rel="noreferrer">Referencia: PROMPERÚ · Inca Jungle ↗</a></details><small>Sin trazado, duración ni precio garantizados en esta web.</small></article><article id="aves" data-reveal><Bird size={34} aria-hidden="true"/><span>02 · BIRDWATCHING</span><h3>Observación de aves.</h3><WildlifePhoto id="cranioleuca"/><p>Los bosques de neblina y los ambientes de Abra Málaga ofrecen oportunidades para observar aves. MINCETUR registra el gallito de las rocas en Pasto Grande y aves como el churrete real y el tijeral de ceja blanca en Abra Málaga.</p><details><summary>Prepara una salida de observación <ArrowUpRight size={18} aria-hidden="true"/></summary><ul><li>Coordina con una guía local el sector, acceso y permisos.</li><li>Lleva binoculares y protección para lluvia; observa sin acercarte a nidos.</li><li>Evita alimentar aves y reproducir sonidos para atraerlas.</li></ul><a href="https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=3700" target="_blank" rel="noreferrer">MINCETUR · Aves de Abra Málaga ↗</a><a href="https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=12460" target="_blank" rel="noreferrer">MINCETUR · Fauna de Pasto Grande ↗</a></details><small>Las especies y avistamientos dependen del sector y de las condiciones.</small></article></div></section>}
function Community(){return <section className="hv-community-editorial" id="experiencias"><div className="hv-editorial-heading" data-reveal><span>ACTIVIDADES LOCALES</span><h2>Productores, alimentación<br/>y celebraciones.</h2></div><div className="hv-community-grid">{[{icon:Users,title:'Conocer a quien produce',body:'Pregunta por el té, el café y el cacao. Compra directamente cuando sea posible y coordina antes de entrar a una parcela.'},{icon:Utensils,title:'Sentarse a la mesa',body:'Pregunta por productos de temporada y preparaciones familiares. Confirma ingredientes si tienes alergias o restricciones alimentarias.'},{icon:Camera,title:'Compartir con respeto',body:'Pide permiso antes de fotografiar. Las celebraciones pertenecen a sus comunidades: sigue sus indicaciones y consulta el programa vigente.'}].map(a=><article key={a.title} data-reveal><a.icon size={30}/><h3>{a.title}</h3><p>{a.body}</p></article>)}</div></section>}
export function TopicExperience({tema}:{tema:string}){return tema==='te'?<ProcessExplorer/>:tema==='cafe'?<ProcessExplorer coffee/>:tema==='wamanmarka'?<Heritage/>:tema==='comunidades'?<><ChapterComplement tema="comunidades"/><Community/><UpcomingCalendar community/><ValleyActivities/></>:<Landscape/>}
export function TopicFilm({tema}:{tema:string}){
 const names:Record<string,string>={te:'tea-harvest',cafe:'coffee-process',wamanmarka:'huamanmarca-visit',comunidades:'culture'};const name=names[tema];
 const raymiVideo='https://d2ol7oe51mr4n9.cloudfront.net/user_3JWz5Wrd1fCUClRS4KqD00b2kRC/7a6f9a98-164c-4939-abdb-994f97284393.mp4';
 const video=useRef<HTMLVideoElement>(null);const [playing,setPlaying]=useState(false),[failed,setFailed]=useState(false);
 useEffect(()=>{const el=video.current;if(!el)return;const io=new IntersectionObserver(entries=>{if(!entries[0].isIntersecting){el.pause();setPlaying(false)}});io.observe(el);const hidden=()=>{if(document.hidden){el.pause();setPlaying(false)}};document.addEventListener('visibilitychange',hidden);return()=>{io.disconnect();el.pause();document.removeEventListener('visibilitychange',hidden)}},[]);
 if(!name)return null;
 async function toggle(){const el=video.current;if(!el)return;if(playing)el.pause();else{setFailed(false);if(!el.getAttribute('src'))el.src=tema==='wamanmarka'?raymiVideo:media+'world/'+name+(window.matchMedia('(max-width: 700px)').matches?'-mobile':'')+'.mp4';if(tema==='wamanmarka'){el.muted=false;el.volume=.65}else el.muted=true;if(el.error)el.load();try{await el.play()}catch{setFailed(true)}}}
 return <section className="hv-topic-film" aria-label="Vídeo del capítulo" data-reveal><video ref={video} poster={media+'world/'+name+'-poster.jpg'} preload="none" playsInline muted loop onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onError={()=>{if(video.current?.error)setFailed(true)}}/><div><span>UNA VENTANA AL CAPÍTULO</span><button onClick={toggle}>{playing?<Pause/>:<Play/>}{failed?'Reintentar vídeo':playing?'Pausar vídeo':'Ver vídeo'}</button><p>{failed?'La imagen y el contenido siguen disponibles.':tema==='wamanmarka'?'Huamanmarca Raymi · música original disponible al reproducir':'Vídeo del recorrido original · sin sonido'}</p></div></section>
}
