import {NatureSection,useEditorialReveal} from './Editorial';
import {UpcomingCalendar} from './calendar/Calendar';
import RouteExplorer from './RouteExplorer';
import IntroShieldCurtain from './IntroShieldCurtain';
import { sitePath } from "@/lib/site";
import { lazy, Suspense, useEffect, useRef, useState } from "react";

import { ScrollScrub } from "@/components/scroll-scrub/scroll-scrub";
import { scrollScrubScenes, scrollScrubTheme } from "@/scroll-scrub-scenes";
const ValleyDirectory = lazy(() => import("@/valley-directory"));

export default function Index({contentRevision=0}:{contentRevision?:number}){
useEditorialReveal();
const mapRef = useRef<HTMLDetailsElement>(null);
const [mapOpen,setMapOpen] = useState(false);
useEffect(() => {
 const revealMap = () => { if (["#mapa", "#quedate", "#mapa-servicios", "#emergencias"].includes(window.location.hash) && mapRef.current) { mapRef.current.open = true; setMapOpen(true); requestAnimationFrame(() => document.getElementById(window.location.hash.slice(1))?.scrollIntoView({block:"start"})); } };
 revealMap(); window.addEventListener("hashchange", revealMap); return () => window.removeEventListener("hashchange", revealMap);
}, []);
return <main className="hv-site"><IntroShieldCurtain/><a className="hv-skip-link" href="#mapa">Ir al mapa y servicios</a>
<header className="hv-nav"><a className="hv-brand" href="#inicio" aria-label="Huayopata Viva, inicio"><img className="hv-official-shield" src={sitePath("assets/identity/escudo-huayopata.webp")} alt="" width="34" height="34"/><span>HUAYOPATA VIVA</span></a><nav aria-label="Navegación principal"><a href="#inicio">Inicio</a><a href="#rutas">Rutas</a><a href={sitePath("/calendario/")}>Calendario</a><a href="#mapa">Mapa y servicios</a></nav><a className="hv-plan-link hv-action hv-action-accent" href="#planifica">Prepara tu visita <span aria-hidden="true">↗</span></a><details className="hv-mobile-menu"><summary aria-label="Abrir menú de navegación">Menú <span aria-hidden="true">+</span></summary><nav aria-label="Navegación móvil" onClick={(event) => { const el = event.currentTarget.closest("details"); if(el) el.open = false; }}><a href="#inicio">Inicio</a><a href="#naturaleza">Descubrir</a><a href={sitePath("/calendario/")}>Calendario</a><a href="#mapa">Mapa y servicios</a><a href="#planifica">Prepara tu visita</a><div className="hv-menu-detail"><span>HISTORIAS DEL VALLE</span><a href={sitePath("/descubre/abra-malaga")}>Abra Málaga</a><a href={sitePath("/descubre/te")}>Té</a><a href={sitePath("/descubre/cafe")}>Café</a><a href={sitePath("/descubre/wamanmarka")}>Wamanmarka</a><a href={sitePath("/descubre/comunidades")}>Comunidades</a></div></nav></details></header>
<div id="inicio"><ScrollScrub scenes={scrollScrubScenes} theme={scrollScrubTheme}/></div>
<section className="hv-manifesto hv-manifesto-impact" aria-labelledby="manifesto-title"><p className="hv-index">HUAYOPATA · CUSCO</p><h2 id="manifesto-title">Donde los Andes<br/><em>se vuelven valle.</em></h2><p>En pocos kilómetros, la altura se convierte en bosque de nubes, cultivos y vida local. Descubre el territorio desde sus propias historias.</p><a className="hv-manifesto-link hv-action hv-action-dark" href="#naturaleza">Descubrir el valle <span aria-hidden="true">↓</span></a></section>
<NatureSection/>
<section className="hv-explore-hub" aria-labelledby="explore-hub-title"><div className="hv-explore-head"><span>HISTORIAS DEL VALLE</span><h2 id="explore-hub-title">Un lugar. Muchas formas de sentirlo.</h2><p>Conoce los cultivos, el patrimonio y las personas que dan vida a Huayopata.</p></div><div className="hv-explore-options"><a href={sitePath("/descubre/te")}><span>01 / EXPERIENCIAS</span><strong>Del cultivo a la taza</strong><small>Té, café y la vida de los productores.</small><b aria-hidden="true">↗</b></a><a href={sitePath("/descubre/wamanmarka")}><span>02 / PATRIMONIO</span><strong>Memoria de piedra</strong><small>Wamanmarka y la historia de Amaybamba.</small><b aria-hidden="true">↗</b></a><a href={sitePath("/descubre/comunidades")}><span>03 / CULTURA VIVA</span><strong>Gente del valle</strong><small>Productores, sabores y encuentros locales.</small><b aria-hidden="true">↗</b></a></div></section>
<RouteExplorer/>
<UpcomingCalendar/>
<section className="hv-map-preview" id="servicios-del-valle" aria-labelledby="map-preview-title">
<div><span>MAPA DEL VALLE</span><h2 id="map-preview-title">Encuentra tu próxima parada.</h2><p>Elige un atractivo, consulta los servicios cercanos y confirma los accesos antes de salir.</p></div>
<details ref={mapRef} className="hv-map-disclosure" onToggle={event=>setMapOpen(event.currentTarget.open)}><summary>Explorar mapa y servicios <b aria-hidden="true">+</b></summary>{mapOpen&&<Suspense fallback={<div className="hv-map-module-loading" role="status">Preparando el directorio y el mapa…</div>}><ValleyDirectory active={mapOpen} contentRevision={contentRevision}/></Suspense>}</details>
</section>
<section className="hv-guide" id="planifica" aria-labelledby="guide-title"><div className="hv-section-head"><span>LO ESENCIAL</span><h2 id="guide-title">Lo justo antes de venir.</h2></div><div className="hv-guide-grid hv-guide-grid-compact">
<article><span>CLIMA</span><h3>Prepárate para el cambio</h3><p>La ruta atraviesa distintos pisos altitudinales. Lleva una capa ligera para lluvia, abrigo y protección solar.</p></article><article><span>CAMINO</span><h3>Consulta antes de salir</h3><p>El estado de la carretera puede variar durante la temporada de lluvias.</p><a href="https://www.gob.pe/sutran" target="_blank" rel="noreferrer">Consultar SUTRAN ↗</a></article><article><span>RESPETO</span><h3>Conoce sin invadir</h3><p>Pide permiso antes de ingresar a cultivos, fotografiar personas o utilizar drones.</p></article></div>
<div className="hv-faq"><h3>Antes de adentrarte</h3><details><summary>¿Puedo visitar una finca sin reservar?</summary><p>Coordina directamente. Las fincas son espacios de trabajo y las visitas, demostraciones y degustaciones dependen del productor y de la temporada.</p><a href="#mapa">Buscar fincas en el directorio ↗</a></details><details><summary>¿Dónde encuentro ayuda durante el viaje?</summary><p>El directorio reúne contactos de emergencia y puntos de atención. La cobertura y la disponibilidad pueden variar.</p><a href="#emergencias">Abrir contactos de emergencia ↗</a></details></div>
<div className="hv-municipal-close hv-municipal-close-impact"><span>HUAYOPATA VIVA</span><strong>Tu próxima historia puede empezar aquí.</strong><p>Elige cuándo venir y conoce qué hace especial a este valle.</p><a className="hv-action hv-action-accent" href={sitePath("/calendario/")}>Ver próximas celebraciones <span aria-hidden="true">↗</span></a></div></section>
<footer className="hv-footer"><div><strong>HUAYOPATA VIVA</strong><p>Una ventana digital al territorio de Huayopata.</p></div><div><span>FUENTES DE REFERENCIA</span><a href="https://www.munihuayopata.gob.pe/" target="_blank" rel="noreferrer">Municipalidad Distrital de Huayopata</a><a href="https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=6915" target="_blank" rel="noreferrer">Inventario MINCETUR: Wamanmarka</a><a href="https://www.gob.pe/munihuayopata" target="_blank" rel="noreferrer">Escudo: ficha institucional en Gob.pe</a></div><p>© 2026 · Cusco, Perú<br/>Proyecto turístico independiente · en desarrollo</p></footer>
</main>}
