import {NatureSection,useEditorialReveal} from './Editorial';
import IntroShieldCurtain from './IntroShieldCurtain';
import { sitePath } from "@/lib/site";
import { useEffect, useRef } from "react";

import { ScrollScrub } from "@/components/scroll-scrub/scroll-scrub";
import { scrollScrubScenes, scrollScrubTheme } from "@/scroll-scrub-scenes";
import ValleyDirectory from "@/valley-directory";

export default function Index({contentRevision=0}:{contentRevision?:number}){
useEditorialReveal();
const mapRef = useRef<HTMLDetailsElement>(null);
useEffect(() => {
 const revealMap = () => { if (["#mapa", "#quedate", "#mapa-servicios", "#emergencias"].includes(window.location.hash) && mapRef.current) { mapRef.current.open = true; requestAnimationFrame(() => document.getElementById(window.location.hash.slice(1))?.scrollIntoView({block:"start"})); } };
 revealMap(); window.addEventListener("hashchange", revealMap); return () => window.removeEventListener("hashchange", revealMap);
}, []);
return <main className="hv-site"><IntroShieldCurtain/><a className="hv-skip-link" href="#mapa">Ir al mapa y servicios</a>
<header className="hv-nav"><a className="hv-brand" href="#inicio" aria-label="Huayopata Viva, inicio"><img className="hv-official-shield" src={sitePath("assets/identity/escudo-huayopata.webp")} alt="Escudo de Huayopata" width="34" height="34"/><span>HUAYOPATA VIVA</span></a><nav aria-label="Navegación principal"><a href="#inicio">Descubre</a><a href="#coffee">Sabores</a><a href="#wamanmarka">Memoria</a><a href="#quedate">Quédate un rato</a><a href="#emergencias">Emergencias</a></nav><a className="hv-plan-link" href="#mapa">Mapa y servicios ↗</a><details className="hv-mobile-menu"><summary aria-label="Abrir menú de navegación">Menú <span aria-hidden="true">+</span></summary><nav aria-label="Navegación móvil" onClick={(event) => { const el = event.currentTarget.closest("details"); if(el) el.open = false; }}><a href={sitePath("/descubre/abra-malaga")}>Abra Málaga</a><a href={sitePath("/descubre/te")}>Mundo del té</a><a href={sitePath("/descubre/cafe")}>Mundo cafetalero</a><a href={sitePath("/descubre/wamanmarka")}>Wamanmarka</a><a href={sitePath("/descubre/comunidades")}>Comunidades</a><a href="#mapa">Mapa y servicios</a><a href="#emergencias">Emergencias</a></nav></details></header>
<div id="inicio"><ScrollScrub scenes={scrollScrubScenes} theme={scrollScrubTheme}/></div>
<section className="hv-manifesto hv-manifesto-impact" aria-labelledby="manifesto-title"><p className="hv-index">HUAYOPATA · CUSCO</p><h2 id="manifesto-title">Donde los Andes<br/><em>se vuelven valle.</em></h2><p>En pocos kilómetros el paisaje cambia por completo. Huayopata conecta altura, niebla, cultivos, memoria y vida local en un mismo valle.</p><a className="hv-manifesto-link" href="#mapa">Explorar servicios y mapa ↓</a></section>
<NatureSection/>
<section className="hv-color-story" aria-labelledby="color-title"><div className="hv-color-heading"><span>OTRAS FORMAS DE SENTIR EL VALLE</span><h2 id="color-title">Sabores que se ven.<br/><em>Historias que se celebran.</em></h2><p>La vida de Huayopata también está en lo que se cultiva, se comparte y se celebra. Detente en sus productores y pregunta por las actividades culturales durante tu visita.</p></div><div className="hv-color-grid"><figure className="hv-color-fruits"><img src="https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/editorial/fruit.webp" alt="Frutas coloridas en un mercado peruano, imagen de contexto" loading="lazy"/><figcaption><span>PRODUCTOS Y SABORES</span><strong>El valle también se prueba.</strong><a href={sitePath("/descubre/comunidades")}>Conocer la vida local ↗</a><small>Imagen de contexto: mercado peruano.</small></figcaption></figure><figure className="hv-color-dance"><img src="https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/editorial/dance.webp" alt="Danza tradicional fotografiada en Cusco, imagen de contexto" loading="lazy"/><figcaption><span>EXPRESIÓN CULTURAL</span><strong>La cultura se vive en compañía.</strong><a href={sitePath("/descubre/comunidades")}>Explorar comunidades ↗</a><small>Imagen de contexto: danza en Cusco.</small></figcaption></figure></div><p className="hv-color-credit">Fotografías de contexto: <a href="https://commons.wikimedia.org/wiki/File:Peruvian_Market_Fruit.jpg" target="_blank" rel="noreferrer">Richard H. Moore, CC BY-SA 4.0</a> y <a href="https://commons.wikimedia.org/wiki/File:Peru_-_Cusco_105_-_school_traditional_dance_festival_(8149453127).jpg" target="_blank" rel="noreferrer">McKay Savage, CC BY 2.0</a>. Imágenes redimensionadas para esta página.</p></section>
<section className="hv-map-preview" id="servicios-del-valle" aria-labelledby="map-preview-title">
<div><span>MAPA DEL VALLE</span><h2 id="map-preview-title">Primero descubre.<br/>Después ubícate.</h2><p>Encuentra lugares para comer, descansar y continuar tu recorrido. Descubre también los atractivos del distrito y consulta sus referencias antes de visitarlos.</p></div>
<details ref={mapRef} className="hv-map-disclosure"><summary onClick={event=>{if(mapRef.current&&!mapRef.current.open){event.preventDefault();mapRef.current.open=true;requestAnimationFrame(()=>document.getElementById("mapa")?.scrollIntoView({block:"start"}));}}}>Explorar mapa y servicios <b>+</b></summary><ValleyDirectory contentRevision={contentRevision}/></details>
</section>
<section className="hv-guide" id="planifica" aria-labelledby="guide-title"><div className="hv-section-head"><span>LO ESENCIAL</span><h2 id="guide-title">Lo justo antes de venir.</h2></div><div className="hv-guide-grid hv-guide-grid-compact">
<article><span>CLIMA</span><h3>Prepárate para el cambio</h3><p>La ruta atraviesa distintos pisos altitudinales. Lleva una capa ligera para lluvia, abrigo y protección solar.</p></article><article><span>CAMINO</span><h3>Consulta antes de salir</h3><p>El estado de la carretera puede variar durante la temporada de lluvias.</p><a href="https://www.gob.pe/sutran" target="_blank" rel="noreferrer">Consultar SUTRAN ↗</a></article><article><span>RESPETO</span><h3>Conoce sin invadir</h3><p>Pide permiso antes de ingresar a cultivos, fotografiar personas o utilizar drones.</p></article></div>
<div className="hv-faq"><h3>Antes de adentrarte</h3><details><summary>¿Puedo visitar una finca sin reservar?</summary><p>Coordina directamente. Las fincas son espacios de trabajo y las visitas, demostraciones y degustaciones dependen del productor y de la temporada.</p><a href="#mapa">Buscar fincas en el directorio ↗</a></details><details><summary>¿Dónde encuentro ayuda durante el viaje?</summary><p>El directorio reúne contactos de emergencia y puntos de atención. La cobertura y la disponibilidad pueden variar.</p><a href="#emergencias">Abrir contactos de emergencia ↗</a></details><details><summary>¿Cómo uso el mapa y guardo un lugar?</summary><p>Abre el mapa, elige una categoría y toca una ficha. El corazón guarda el lugar en este navegador; puedes descargar tus guardados como texto.</p><a href="#mapa">Abrir el mapa ↗</a></details></div>
<div className="hv-municipal-close hv-municipal-close-impact"><span>HUAYOPATA VIVA</span><strong>Tu próxima historia puede empezar aquí.</strong><p>Una taza con origen, un camino entre nubes y un valle que merece conocerse con calma.</p><a href="#inicio">Volver al inicio ↑</a></div></section>
<footer className="hv-footer"><div><strong>HUAYOPATA VIVA</strong><p>Una ventana digital al territorio de Huayopata.</p></div><div><span>FUENTES DE REFERENCIA</span><a href="https://www.munihuayopata.gob.pe/" target="_blank" rel="noreferrer">Municipalidad Distrital de Huayopata</a><a href="https://consultasenlinea.mincetur.gob.pe/fichaInventario/index.aspx?cod_Ficha=6915" target="_blank" rel="noreferrer">Inventario MINCETUR: Wamanmarka</a><a href="https://www.gob.pe/munihuayopata" target="_blank" rel="noreferrer">Escudo: ficha institucional en Gob.pe</a></div><p>© 2026 · Cusco, Perú<br/>Proyecto turístico independiente · en desarrollo</p></footer>
</main>}
