import {useEffect,useState} from 'react';
import {ArrowUpRight,Camera,MapPin} from 'lucide-react';
import {sitePath} from './lib/site';
import './local-gallery.css';
const photo='https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/calendar/wamanmarka.webp';
export default function LocalGallery(){
 const [enlarge,setEnlarge]=useState(false);
 useEffect(()=>{if(!enlarge)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setEnlarge(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[enlarge]);
 return <section className="hv-local-gallery" id="galeria" aria-labelledby="gallery-title"><div className="hv-gallery-heading" data-reveal><span>HUAYOPATA EN IMÁGENES</span><h2 id="gallery-title">Un territorio con nombre propio.</h2><p>Un archivo visual que crecerá con fotografías del distrito y autorización de sus autores. Cada imagen debe mostrar el lugar que identifica.</p></div><div className="hv-gallery-grid"><figure className="hv-gallery-feature" data-reveal><button onClick={()=>setEnlarge(true)} aria-label="Ampliar fotografía documental de Wamanmarka"><img src={photo} alt="Sitio arqueológico Wamanmarka en Huayopata, fotografía de 2007" loading="lazy"/><span className="hv-gallery-expand"><Camera size={17}/> Ampliar fotografía</span></button><figcaption><span><MapPin size={16}/> WAMANMARKA · HUAYOPATA</span><strong>Memoria que permanece en el paisaje.</strong><small>Fotografía de AgainErick, 2007 · CC BY-SA 3.0. Muestra el sitio, no una festividad.</small><a href={sitePath('/descubre/wamanmarka')}>Conocer Wamanmarka <ArrowUpRight size={17}/></a></figcaption></figure><div className="hv-gallery-side" data-reveal><article><span>LOS SABORES</span><h3>El té y el café cuentan historias de trabajo.</h3><p>Conoce las experiencias productivas y a sus protagonistas.</p><a href={sitePath('/descubre/te')}>Mundo del té <ArrowUpRight size={17}/></a><a href={sitePath('/descubre/cafe')}>Mundo del café <ArrowUpRight size={17}/></a></article><article><span>CULTURA VIVA</span><h3>Un calendario de encuentros.</h3><p>Fiestas, instituciones y comunidades: consulta las fechas y programas disponibles.</p><a href={sitePath('/calendario/')}>Explorar el calendario <ArrowUpRight size={17}/></a></article></div></div><p className="hv-gallery-credit">Fuente fotográfica: <a href="https://commons.wikimedia.org/wiki/File:Huamanmarka_Archaeological_site.jpg" target="_blank" rel="noreferrer">AgainErick / Wikimedia Commons</a> · <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noreferrer">CC BY-SA 3.0</a>. Archivo redimensionado para la web.</p>{enlarge&&<div className="hv-gallery-lightbox" role="dialog" aria-modal="true" aria-label="Fotografía de Wamanmarka" onClick={()=>setEnlarge(false)}><button onClick={()=>setEnlarge(false)} aria-label="Cerrar fotografía">Cerrar ×</button><img src={photo} alt="Wamanmarka, Huayopata, en 2007" onClick={e=>e.stopPropagation()}/><p>Wamanmarka · AgainErick, 2007 · CC BY-SA 3.0</p></div>}</section>
}
