import { sitePath } from "@/lib/site";
import { createElement } from "react";
import {Bike,Bird,ArrowUpRight} from "lucide-react";
import type { ScrollScrubScene, ScrollScrubTheme } from "@/components/scroll-scrub/scroll-scrub";
export const scrollScrubTheme: ScrollScrubTheme = { accent:"#D7F36B", background:"#062F26", ink:"#F4F0D8", muted:"#DDE7DF" };
const explore = (path: string, label: string) => createElement("a", { href: sitePath(`/descubre/${path}`), className: "hv-story-button" }, label, createElement("span", {className:"hv-action-arrow", "aria-hidden":true}, "↗"));
const valleyActions=createElement("div",{className:"hv-valley-actions"},
 createElement("a",{href:sitePath("/descubre/comunidades/#ciclismo")},createElement(Bike,{size:18,"aria-hidden":true}),"Descenso en bicicleta",createElement(ArrowUpRight,{size:16,"aria-hidden":true})),
 createElement("a",{href:sitePath("/descubre/comunidades/#aves")},createElement(Bird,{size:18,"aria-hidden":true}),"Observación de aves",createElement(ArrowUpRight,{size:16,"aria-hidden":true}))
);
export const scrollScrubScenes: ScrollScrubScene[] = [
{id:"abra",playback:"autoplay",label:"Abra Málaga",kicker:"01 · Geografía",title:"Huayopata y Abra Málaga",body:"Consulta información sobre los bosques, las aves y las condiciones de visita del sector Abra Málaga.",clip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/huayopata-intro.mp4",poster:sitePath("assets/world/huayopata-intro-poster.webp"),mobileClip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/huayopata-intro-mobile.mp4",mobilePoster:sitePath("assets/world/huayopata-intro-mobile-poster.webp"),tags:["Cusco","Ceja de selva"],actions:explore("abra-malaga","Bosques y aves de Abra Málaga"),scroll:1.8},
{id:"tea",playback:"autoplay",label:"Té",kicker:"02 · Producción de té",title:"Cultivo y elaboración del té",body:"En Huyro se produce té negro y té verde. Consulta con los productores las actividades disponibles para visitantes.",clip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/tea-harvest.mp4",poster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/tea-harvest-poster.jpg",mobileClip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/tea-harvest-mobile.mp4",mobilePoster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/tea-harvest-mobile-poster.jpg",tags:["Agroturismo","Cosecha"],actions:explore("te","Cultivo y elaboración del té"),align:"left",scroll:2.2,linger:0.15},
{id:"coffee",playback:"autoplay",label:"Café",kicker:"03 · Producción de café",title:"Cosecha y procesamiento del café",body:"Conoce las etapas de recolección y beneficio. El método de procesamiento y la atención dependen de cada finca.",clip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/coffee-process.mp4",poster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/coffee-process-poster.jpg",mobileClip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/coffee-process-mobile.mp4",mobilePoster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/coffee-process-mobile-poster.jpg",mobileObjectPosition:"60% 50%",tags:["Café de especialidad","Experiencia local"],actions:explore("cafe","Cosecha y beneficio del café"),scroll:2.3,linger:0.12},
{id:"wamanmarka",playback:"autoplay",label:"Wamanmarka",kicker:"04 · Arqueología",title:"Wamanmarka: patrimonio inca",body:"El conjunto conserva recintos, un patio central y un ushnu vinculados a la administración del valle de Amaybamba.",clip:"https://d2ol7oe51mr4n9.cloudfront.net/user_3JWz5Wrd1fCUClRS4KqD00b2kRC/7a6f9a98-164c-4939-abdb-994f97284393.mp4",poster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/huamanmarca-visit-poster.jpg",mobileClip:"https://d2ol7oe51mr4n9.cloudfront.net/user_3JWz5Wrd1fCUClRS4KqD00b2kRC/7a6f9a98-164c-4939-abdb-994f97284393.mp4",mobilePoster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/huamanmarca-visit-mobile-poster.jpg",tags:["Patrimonio cultural","Historia viva"],actions:explore("wamanmarka","Historia y arquitectura de Wamanmarka"),align:"right",scroll:1.7},
{id:"community",playback:"autoplay",label:"Comunidades",kicker:"05 · Comunidades",title:"Actividades en Huayopata",body:"Consulta las celebraciones documentadas y la información para organizar salidas de ciclismo y observación de aves.",clip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/culture.mp4",poster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/culture-poster.jpg",mobileClip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/culture-mobile.mp4",mobilePoster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/culture-mobile-poster.jpg",tags:["Cultura","Sabores"],actions:valleyActions,scroll:1.7}
];
