import { sitePath } from "@/lib/site";
import { createElement } from "react";
import {Bike,Bird,ArrowUpRight} from "lucide-react";
import type { ScrollScrubScene, ScrollScrubTheme } from "@/components/scroll-scrub/scroll-scrub";
export const scrollScrubTheme: ScrollScrubTheme = { accent:"#D7F36B", background:"#062F26", ink:"#F4F0D8", muted:"#DDE7DF" };
const explore = (path: string, label: string) => createElement("a", { href: sitePath(`/descubre/${path}`), className: "hv-story-button" }, label, " ↗");
const valleyActions=createElement("div",{className:"hv-valley-actions"},
 createElement("a",{href:sitePath("/descubre/comunidades/#ciclismo")},createElement(Bike,{size:18,"aria-hidden":true}),"Descenso en bicicleta",createElement(ArrowUpRight,{size:16,"aria-hidden":true})),
 createElement("a",{href:sitePath("/descubre/comunidades/#aves")},createElement(Bird,{size:18,"aria-hidden":true}),"Observación de aves",createElement(ArrowUpRight,{size:16,"aria-hidden":true}))
);
export const scrollScrubScenes: ScrollScrubScene[] = [
{id:"abra",playback:"autoplay",label:"Abra Málaga",kicker:"01 · El umbral",title:"Aquí los Andes cambian de voz.",body:"Desciende del aire frío de la cordillera hacia un valle donde la niebla alimenta otra forma de vida.",clip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/huayopata-intro.mp4",poster:sitePath("assets/world/huayopata-intro-poster.webp"),mobileClip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/huayopata-intro-mobile.mp4",mobilePoster:sitePath("assets/world/huayopata-intro-mobile-poster.webp"),tags:["Cusco","Ceja de selva"],actions:explore("abra-malaga","Explorar Abra Málaga"),scroll:1.8},
{id:"tea",playback:"autoplay",label:"Té",kicker:"02 · Hojas de altura",title:"El valle se bebe hoja por hoja.",body:"Conoce la tradición del té y el trabajo de las familias que mantienen vivo su cultivo.",clip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/tea-harvest.mp4",poster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/tea-harvest-poster.jpg",mobileClip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/tea-harvest-mobile.mp4",mobilePoster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/tea-harvest-mobile-poster.jpg",tags:["Agroturismo","Cosecha"],actions:explore("te","Mundo del té"),align:"left",scroll:2.2,linger:0.15},
{id:"coffee",playback:"autoplay",label:"Café",kicker:"03 · Fruto rojo",title:"Del cafetal a una taza con origen.",body:"Camina entre cafetos y descubre procesos artesanales junto a productores locales.",clip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/coffee-process.mp4",poster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/coffee-process-poster.jpg",mobileClip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/coffee-process-mobile.mp4",mobilePoster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/coffee-process-mobile-poster.jpg",mobileObjectPosition:"60% 50%",tags:["Café de especialidad","Experiencia local"],actions:explore("cafe","Mundo cafetalero"),scroll:2.3,linger:0.12},
{id:"wamanmarka",playback:"autoplay",label:"Wamanmarka",kicker:"04 · Memoria de piedra",title:"Antes del camino, ya existía un encuentro.",body:"Wamanmarka conserva arquitectura inca y la memoria del valle de Amaybamba.",clip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/huamanmarca-visit.mp4",poster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/huamanmarca-visit-poster.jpg",mobileClip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/huamanmarca-visit-mobile.mp4",mobilePoster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/huamanmarca-visit-mobile-poster.jpg",tags:["Patrimonio cultural","Historia viva"],actions:explore("wamanmarka","Descubrir Wamanmarka"),align:"right",scroll:1.7},
{id:"community",playback:"autoplay",label:"Comunidades",kicker:"05 · El valle vivo",title:"El destino no termina en el paisaje.",body:"Sabores, relatos y hospitalidad convierten cada visita en un intercambio con Huayopata.",clip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/culture.mp4",poster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/culture-poster.jpg",mobileClip:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/culture-mobile.mp4",mobilePoster:"https://rhghpitzpdstrraxuogz.supabase.co/storage/v1/object/public/huayopata-media/assets/world/culture-mobile-poster.jpg",tags:["Cultura","Sabores"],actions:valleyActions,scroll:1.7}
];
