export interface ServicePlace {image?:string;topic?:string;coordinateSource?:string;id:string;name:string;category:string;kind:string;area:string;lat:number|null;lng:number|null;description:string;source:string;sourceLabel:string;note:string;phone?:string|null;phoneDisplay?:string;phoneSource?:string;contactOnly?:boolean;whatsapp?:string|null}
export const servicePlaces:ServicePlace[] = [
  {
    "id": "node-5642053422",
    "name": "Banco Nacional",
    "category": "servicios",
    "kind": "Banco",
    "area": "Huyro y alrededores",
    "lat": -13.0068102,
    "lng": -72.5536308,
    "description": "Un punto de apoyo para tu paso por Huayopata.",
    "source": "https://www.openstreetmap.org/node/5642053422",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-5642100022",
    "name": "Horacio Echegaray",
    "category": "servicios",
    "kind": "Compras",
    "area": "Huyro y alrededores",
    "lat": -13.0064329,
    "lng": -72.5537007,
    "description": "Un punto de apoyo para tu paso por Huayopata.",
    "source": "https://www.openstreetmap.org/node/5642100022",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-5642160221",
    "name": "Brayan",
    "category": "dormir",
    "kind": "Hospedaje",
    "area": "Huyro y alrededores",
    "lat": -13.0055688,
    "lng": -72.5547924,
    "description": "Una opción de alojamiento registrada en el valle. Consulta directamente habitaciones y servicios.",
    "source": "https://www.openstreetmap.org/node/5642160221",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-5642160522",
    "name": "Centro de Salud de Huyro",
    "category": "emergencias",
    "kind": "Salud",
    "area": "Huyro y alrededores",
    "lat": -13.0074028,
    "lng": -72.5554068,
    "description": "Un punto de apoyo para tu paso por Huayopata.",
    "source": "https://www.openstreetmap.org/node/5642160522",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-5657324626",
    "name": "Dulce amanecer",
    "category": "dormir",
    "kind": "Hospedaje",
    "area": "Huyro y alrededores",
    "lat": -13.0059314,
    "lng": -72.5546808,
    "description": "Una opción de alojamiento registrada en el valle. Consulta directamente habitaciones y servicios.",
    "source": "https://www.openstreetmap.org/node/5657324626",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-5657348321",
    "name": "Señor de huanca",
    "category": "comer",
    "kind": "Restaurante",
    "area": "Huyro y alrededores",
    "lat": -13.0059739,
    "lng": -72.554876,
    "description": "Una parada para comer o tomar algo durante tu paso por el valle. Consulta la atención del día.",
    "source": "https://www.openstreetmap.org/node/5657348321",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-5657352521",
    "name": "Pollería la pechugona",
    "category": "comer",
    "kind": "Restaurante",
    "area": "Huyro y alrededores",
    "lat": -13.0057579,
    "lng": -72.5545627,
    "description": "Una parada para comer o tomar algo durante tu paso por el valle. Consulta la atención del día.",
    "source": "https://www.openstreetmap.org/node/5657352521",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-5677728834",
    "name": "Picchulin",
    "category": "comer",
    "kind": "Panadería",
    "area": "Huyro y alrededores",
    "lat": -13.0058776,
    "lng": -72.5525863,
    "description": "Una parada para comer o tomar algo durante tu paso por el valle. Consulta la atención del día.",
    "source": "https://www.openstreetmap.org/node/5677728834",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-5677737227",
    "name": "Mijuy wasi",
    "category": "comer",
    "kind": "Restaurante",
    "area": "Huyro y alrededores",
    "lat": -13.0058158,
    "lng": -72.5537375,
    "description": "Una parada para comer o tomar algo durante tu paso por el valle. Consulta la atención del día.",
    "source": "https://www.openstreetmap.org/node/5677737227",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-5678392625",
    "name": "Cohapa",
    "category": "dormir",
    "kind": "Alojamiento",
    "area": "Huyro y alrededores",
    "lat": -13.0045758,
    "lng": -72.5577717,
    "description": "Una opción de alojamiento registrada en el valle. Consulta directamente habitaciones y servicios.",
    "source": "https://www.openstreetmap.org/node/5678392625",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-5757244722",
    "name": "La mixtura",
    "category": "comer",
    "kind": "Restaurante",
    "area": "Huyro y alrededores",
    "lat": -13.0068385,
    "lng": -72.5545131,
    "description": "Una parada para comer o tomar algo durante tu paso por el valle. Consulta la atención del día.",
    "source": "https://www.openstreetmap.org/node/5757244722",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-5766008154",
    "name": "Mr. Rogelio",
    "category": "comer",
    "kind": "Restaurante",
    "area": "Huyro y alrededores",
    "lat": -13.0066179,
    "lng": -72.5545528,
    "description": "Una parada para comer o tomar algo durante tu paso por el valle. Consulta la atención del día.",
    "source": "https://www.openstreetmap.org/node/5766008154",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-5850001714",
    "name": "Migael",
    "category": "servicios",
    "kind": "Combustible",
    "area": "Huyro y alrededores",
    "lat": -12.9983048,
    "lng": -72.5442403,
    "description": "Un punto de apoyo para tu paso por Huayopata.",
    "source": "https://www.openstreetmap.org/node/5850001714",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-6311585587",
    "name": "Koricancha",
    "category": "dormir",
    "kind": "Hospedaje",
    "area": "Huyro y alrededores",
    "lat": -13.0055456,
    "lng": -72.5550466,
    "description": "Una opción de alojamiento registrada en el valle. Consulta directamente habitaciones y servicios.",
    "source": "https://www.openstreetmap.org/node/6311585587",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-6311591985",
    "name": "Municipio de Huyro",
    "category": "servicios",
    "kind": "Información local",
    "area": "Huyro y alrededores",
    "lat": -13.0038818,
    "lng": -72.5491274,
    "description": "Un punto de apoyo para tu paso por Huayopata.",
    "source": "https://www.openstreetmap.org/node/6311591985",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-6401590485",
    "name": "Essalud",
    "category": "emergencias",
    "kind": "Salud",
    "area": "Huyro y alrededores",
    "lat": -13.0066105,
    "lng": -72.5551005,
    "description": "Un punto de apoyo para tu paso por Huayopata.",
    "source": "https://www.openstreetmap.org/node/6401590485",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-9118327309",
    "name": "Casa de la Mamá",
    "category": "dormir",
    "kind": "Hospedaje",
    "area": "Huyro y alrededores",
    "lat": -12.9974332,
    "lng": -72.5337219,
    "description": "Una opción de alojamiento registrada en el valle. Consulta directamente habitaciones y servicios.",
    "source": "https://www.openstreetmap.org/node/9118327309",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-9118339248",
    "name": "Petro Dut",
    "category": "servicios",
    "kind": "Combustible",
    "area": "Huyro y alrededores",
    "lat": -12.9986811,
    "lng": -72.5421073,
    "description": "Un punto de apoyo para tu paso por Huayopata.",
    "source": "https://www.openstreetmap.org/node/9118339248",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-12750345801",
    "name": "Elvira Infusiones",
    "category": "sabores",
    "kind": "Té de origen",
    "area": "Huyro y alrededores",
    "lat": -12.99915,
    "lng": -72.5462345,
    "description": "Té e infusiones del valle: una parada para conocer productos de origen.",
    "source": "https://www.openstreetmap.org/node/12750345801",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": "+51986021394"
  },
  {
    "id": "node-12766399701",
    "name": "Colectivos a Santa María y Santa Teresa",
    "category": "servicios",
    "kind": "Transporte",
    "area": "Huyro y alrededores",
    "lat": -13.0058047,
    "lng": -72.5544682,
    "description": "Un punto de apoyo para tu paso por Huayopata.",
    "source": "https://www.openstreetmap.org/node/12766399701",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-13287893101",
    "name": "Ipal Lodge",
    "category": "dormir",
    "kind": "Hospedaje",
    "area": "Huyro y alrededores",
    "lat": -12.9981297,
    "lng": -72.5420099,
    "description": "Una opción de alojamiento registrada en el valle. Consulta directamente habitaciones y servicios.",
    "source": "https://www.openstreetmap.org/node/13287893101",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "way-227925302",
    "name": "Comisaría PNP Huyro",
    "category": "emergencias",
    "kind": "Comisaría",
    "area": "Huyro y alrededores",
    "lat": -13.00656786,
    "lng": -72.5533744,
    "description": "Comisaría de Huyro. Contacto policial local publicado por la Municipalidad Distrital de Huayopata.",
    "source": "https://www.openstreetmap.org/way/227925302",
    "sourceLabel": "OpenStreetMap",
    "note": "Ubicación: OpenStreetMap. Teléfono: directorio oficial municipal, consultado el 28/09/2026.",
    "phone": "+51980122033",
    "phoneDisplay": "980 122 033",
    "phoneSource": "https://www.gob.pe/institucion/munihuayopata/contacto-y-numeros-de-emergencias"
  },
  {
    "id": "way-227925321",
    "name": "Municipalidad de Huyro",
    "category": "servicios",
    "kind": "Información local",
    "area": "Huyro y alrededores",
    "lat": -13.00663796,
    "lng": -72.55359036,
    "description": "Un punto de apoyo para tu paso por Huayopata.",
    "source": "https://www.openstreetmap.org/way/227925321",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "way-594374998",
    "name": "Mercado de Abastos de Huyro",
    "category": "comer",
    "kind": "Mercado",
    "area": "Huyro y alrededores",
    "lat": -13.006122399999999,
    "lng": -72.55424938,
    "description": "Una parada para comer o tomar algo durante tu paso por el valle. Consulta la atención del día.",
    "source": "https://www.openstreetmap.org/way/594374998",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-4972252425",
    "name": "Refrigerios Rubi",
    "category": "comer",
    "kind": "Restaurante",
    "area": "Amaybamba",
    "lat": -13.0051984,
    "lng": -72.5090747,
    "description": "Una parada para comer o tomar algo durante tu paso por el valle. Consulta la atención del día.",
    "source": "https://www.openstreetmap.org/node/4972252425",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-9118327311",
    "name": "Alexsu's",
    "category": "comer",
    "kind": "Restaurante",
    "area": "Alfamayo",
    "lat": -13.0659631,
    "lng": -72.403252,
    "description": "Una parada para comer o tomar algo durante tu paso por el valle. Consulta la atención del día.",
    "source": "https://www.openstreetmap.org/node/9118327311",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-9118331691",
    "name": "La Casa del Té",
    "category": "comer",
    "kind": "Café y té",
    "area": "Amaybamba",
    "lat": -13.0008262,
    "lng": -72.5278123,
    "description": "Una parada para comer o tomar algo durante tu paso por el valle. Consulta la atención del día.",
    "source": "https://www.openstreetmap.org/node/9118331691",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "node-9118341232",
    "name": "Tambo de Verónica",
    "category": "comer",
    "kind": "Restaurante",
    "area": "Alfamayo",
    "lat": -13.0633934,
    "lng": -72.409899,
    "description": "Una parada para comer o tomar algo durante tu paso por el valle. Consulta la atención del día.",
    "source": "https://www.openstreetmap.org/node/9118341232",
    "sourceLabel": "OpenStreetMap",
    "note": "Registro cartográfico; horario y operación no confirmados.",
    "phone": null
  },
  {
    "id": "guardian",
    "name": "The Guardian Farm",
    "category": "sabores",
    "kind": "Finca",
    "area": "Huayopata",
    "lat": -13.00874,
    "lng": -72.57028,
    "description": "Finca registrada también como El Establo. Coordina el acceso antes de visitar.",
    "source": "https://mapcarta.com/N5657269821",
    "sourceLabel": "Referencia pública",
    "note": "Confirma acceso, atención y disponibilidad con el establecimiento.",
    "phone": null,
    "whatsapp": null
  },
  {
    "id": "experiencia-te",
    "name": "Experiencia del té",
    "category": "sabores",
    "kind": "Visita a productores",
    "area": "Valle de Huyro",
    "lat": null,
    "lng": null,
    "description": "Conoce el cultivo y la elaboración del té con una experiencia coordinada por Impactful Travel.",
    "source": "https://impactful.travel/tour/the-peruvian-tea-experience/",
    "sourceLabel": "Referencia pública",
    "note": "Confirma acceso, atención y disponibilidad con el establecimiento.",
    "phone": null,
    "whatsapp": null
  },
  {
    "id": "julia",
    "name": "La Chakra de Julia",
    "category": "sabores",
    "kind": "Café y cacao",
    "area": "Huayopata",
    "lat": null,
    "lng": null,
    "description": "Café, cacao y vida rural junto a una familia productora. Contacta a Julia para coordinar la visita.",
    "source": "https://kinachocolates.com/es/talleres-barcelona/vive-el-cacao-y-el-cafe-desde-su-origen-en-la-chakra-de-julia",
    "sourceLabel": "Referencia pública",
    "note": "Confirma acceso, atención y disponibilidad con el establecimiento.",
    "phone": "+51993780365",
    "whatsapp": "https://wa.me/51993780365"
  },
  {
    "id": "finca-ecologica",
    "name": "Finca Ecológica Huyro",
    "category": "sabores",
    "kind": "Agroecología",
    "area": "Huyro",
    "lat": null,
    "lng": null,
    "description": "Proyecto de sostenibilidad y aprendizaje rural. Consulta si recibe visitas antes de acercarte.",
    "source": "https://gruporural-seedcenter.pucp.edu.pe/living-lab-huyro",
    "sourceLabel": "Referencia pública",
    "note": "Confirma acceso, atención y disponibilidad con el establecimiento.",
    "phone": null,
    "whatsapp": null
  },
  {
    "id": "tunkiwasi",
    "name": "Tunkiwasi Lodge",
    "category": "dormir",
    "kind": "Naturaleza y aves",
    "area": "Inkatambo",
    "lat": null,
    "lng": null,
    "description": "Búngalos entre vegetación, senderos y espacios para observar aves. En el km 178 de la carretera a Quillabamba.",
    "source": "https://tunkiwasilodge.com/",
    "sourceLabel": "Sitio del establecimiento",
    "note": "Confirma acceso, atención y disponibilidad con el establecimiento.",
    "phone": "+51974724914",
    "whatsapp": null
  },
  {
    "id": "casablanca",
    "name": "Casa Blanca Vintage",
    "category": "dormir",
    "kind": "Lodge",
    "area": "Calquiña",
    "lat": null,
    "lng": null,
    "description": "Un alojamiento rodeado de naturaleza, presentado por la Municipalidad de Huayopata.",
    "source": "https://www.gob.pe/institucion/munihuayopata/noticias/771323-distrito-de-huayopata-puerta-de-ingreso-a-la-amazonia-inka",
    "sourceLabel": "Municipalidad de Huayopata",
    "note": "Confirma acceso, atención y disponibilidad con el establecimiento.",
    "phone": null,
    "whatsapp": null
  },
  {
    "id": "lucumayo",
    "name": "Lucumayo Lodge",
    "category": "dormir",
    "kind": "Lodge",
    "area": "Amaybamba",
    "lat": null,
    "lng": null,
    "description": "Alojamiento en la ruta Cusco–Quillabamba, en el centro poblado de Amaybamba.",
    "source": "https://www.google.com.pe/travel/hotels/entity/CgsIk6SFqMuGs7rTARAB",
    "sourceLabel": "Referencia pública",
    "note": "Confirma acceso, atención y disponibilidad con el establecimiento.",
    "phone": "+51948620109",
    "whatsapp": null
  },
  {
    "id": "waranway",
    "name": "Waranway Lodge",
    "category": "dormir",
    "kind": "Lodge",
    "area": "Huayopata",
    "lat": null,
    "lng": null,
    "description": "Una alternativa de alojamiento para hacer una pausa en el distrito. Consulta la ubicación con el alojamiento.",
    "source": "https://www.google.com.pe/travel/hotels/entity/CgsIr-z66Zi0kvHkARAB",
    "sourceLabel": "Referencia pública",
    "note": "Confirma acceso, atención y disponibilidad con el establecimiento.",
    "phone": null,
    "whatsapp": null
  },
  {
    "id": "soncco",
    "name": "Soncco Lodge Restaurant",
    "category": "dormir",
    "kind": "Lodge y restaurante",
    "area": "Huertahuaycco",
    "lat": null,
    "lng": null,
    "description": "Hospedaje con restaurante en la comunidad de Huertahuaycco. Consulta el acceso y la atención.",
    "source": "https://www.trip.com/hotels/la-convencion-province-hotel-detail-113531506/soncco-lodge/",
    "sourceLabel": "Referencia pública",
    "note": "Confirma acceso, atención y disponibilidad con el establecimiento.",
    "phone": null,
    "whatsapp": null
  },
  {
    "id": "ecolux",
    "name": "Huyro Ecolux The Green Garden",
    "category": "dormir",
    "kind": "Hospedaje",
    "area": "Huyro",
    "lat": null,
    "lng": null,
    "description": "Alojamiento registrado en Huayopata. Consulta disponibilidad y ubicación antes de salir.",
    "source": "https://www.tripadvisor.com/Hotel_Review-g23226474-d23225280-Reviews-Huyro_Ecolux_the_Green_Garden-Huayopata_Cusco_Region.html",
    "sourceLabel": "Referencia pública",
    "note": "Confirma acceso, atención y disponibilidad con el establecimiento.",
    "phone": null,
    "whatsapp": null
  },
  {
    "id": "cochapata",
    "name": "Cochapata Lodge",
    "category": "dormir",
    "kind": "Lodge",
    "area": "Huyro y alrededores",
    "lat": -13.00522,
    "lng": -72.54591,
    "description": "Alojamiento en el entorno rural de Huyro. Coordina el acceso directamente.",
    "source": "https://mapcarta.com/N5677728835",
    "sourceLabel": "Referencia pública",
    "note": "Confirma acceso, atención y disponibilidad con el establecimiento.",
    "phone": null,
    "whatsapp": null
  },
  {
    "id": "emergencia-seguridad",
    "name": "Seguridad Ciudadana de Huayopata",
    "category": "emergencias",
    "kind": "Serenazgo / seguridad ciudadana",
    "area": "Huayopata · contacto local",
    "lat": null,
    "lng": null,
    "description": "Contacto municipal de Seguridad Ciudadana para solicitar apoyo local.",
    "source": "https://www.gob.pe/institucion/munihuayopata/contacto-y-numeros-de-emergencias",
    "sourceLabel": "Municipalidad de Huayopata",
    "note": "Contacto consultado en fuente oficial el 28/09/2026. La respuesta depende de la cobertura y disponibilidad del servicio.",
    "phone": "+51991796354",
    "phoneDisplay": "991 796 354",
    "contactOnly": true
  },
  {
    "id": "emergencia-pnp",
    "name": "Policía Nacional del Perú",
    "category": "emergencias",
    "kind": "Central policial",
    "area": "Perú · central de emergencias",
    "lat": null,
    "lng": null,
    "description": "Para solicitar intervención policial ante delitos o situaciones de peligro.",
    "source": "https://www.gob.pe/institucion/pnp/contacto-y-numeros-de-emergencias",
    "sourceLabel": "Policía Nacional del Perú",
    "note": "Contacto consultado en fuente oficial el 28/09/2026. La respuesta depende de la cobertura y disponibilidad del servicio.",
    "phone": "105",
    "phoneDisplay": "105",
    "contactOnly": true
  },
  {
    "id": "emergencia-bomberos",
    "name": "Bomberos",
    "category": "emergencias",
    "kind": "Incendios y rescate",
    "area": "Perú · central de emergencias",
    "lat": null,
    "lng": null,
    "description": "Central de emergencias de los Bomberos Voluntarios para incendios y rescates.",
    "source": "https://sgonorte.bomberosperu.gob.pe/24horas",
    "sourceLabel": "Cuerpo General de Bomberos Voluntarios del Perú",
    "note": "Contacto consultado en fuente oficial el 28/09/2026. La respuesta depende de la cobertura y disponibilidad del servicio.",
    "phone": "116",
    "phoneDisplay": "116",
    "contactOnly": true
  },
  {
    "id": "emergencia-samu",
    "name": "SAMU · urgencias médicas",
    "category": "emergencias",
    "kind": "Ambulancia / orientación de urgencia",
    "area": "Cusco · central SAMU",
    "lat": null,
    "lng": null,
    "description": "El operador evalúa la urgencia médica y coordina la respuesta según cobertura. No garantiza una ambulancia disponible en Huayopata.",
    "source": "https://diresacusco.gob.pe/bdata/emergencias/BOLETIN_DPCED1_%20SEMESTRE_2024.pdf",
    "sourceLabel": "Gerencia Regional de Salud Cusco",
    "note": "Contacto consultado en fuente oficial el 28/09/2026. La respuesta depende de la cobertura y disponibilidad del servicio.",
    "phone": "106",
    "phoneDisplay": "106",
    "contactOnly": true
  },
  {
    "id": "emergencia-linea100",
    "name": "Línea 100",
    "category": "emergencias",
    "kind": "Violencia familiar y sexual",
    "area": "Perú · atención especializada",
    "lat": null,
    "lng": null,
    "description": "Orientación y apoyo ante violencia contra las mujeres e integrantes del grupo familiar. Ante peligro inmediato, llama también al 105.",
    "source": "https://www.gob.pe/479-servicios-para-atender-casos-de-violencia-contra-las-mujeres-e-integrantes-del-grupo-familiar",
    "sourceLabel": "Ministerio de la Mujer y Poblaciones Vulnerables",
    "note": "Contacto consultado en fuente oficial el 28/09/2026. La respuesta depende de la cobertura y disponibilidad del servicio.",
    "phone": "100",
    "phoneDisplay": "100",
    "contactOnly": true
  },
  {
    "id": "emergencia-carreteras",
    "name": "Policía de Carreteras",
    "category": "emergencias",
    "kind": "Emergencia en carretera",
    "area": "Perú · red vial",
    "lat": null,
    "lng": null,
    "description": "Contacto policial para emergencias en carretera. Indica la vía, el kilómetro o un punto de referencia.",
    "source": "https://www.gob.pe/institucion/pnp/contacto-y-numeros-de-emergencias",
    "sourceLabel": "Policía Nacional del Perú",
    "note": "Contacto consultado en fuente oficial el 28/09/2026. La respuesta depende de la cobertura y disponibilidad del servicio.",
    "phone": "110",
    "phoneDisplay": "110",
    "contactOnly": true
  }
];
