import {useEffect,useState} from 'react';
import {sitePath} from './lib/site';
import './site-header.css';
type Section='home'|'stories'|'calendar';
export default function SiteHeader({section='home'}:{section?:Section}){
 const [active,setActive]=useState('');
 useEffect(()=>{if(section!=='home')return;const nodes=['inicio','naturaleza','rutas','mapa','planifica'].map(id=>document.getElementById(id)).filter((el):el is HTMLElement=>!!el);if(!nodes.length)return;const io=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)setActive(entry.target.id)},{rootMargin:'-22% 0px -65% 0px'});nodes.forEach(n=>io.observe(n));return()=>io.disconnect()},[section]);
 const anchor=(id:string)=>section==='home'?'#'+id:sitePath('/#'+id);
 const items=[{id:'inicio',label:'Inicio',href:anchor('inicio')},{id:'naturaleza',label:'Descubrir',href:anchor('naturaleza')},{id:'rutas',label:'Rutas',href:anchor('rutas')},{id:'calendar',label:'Calendario',href:sitePath('/calendario/')},{id:'mapa',label:'Mapa y servicios',href:anchor('mapa')}];
 return <header className="hv-nav hv-global-nav"><a className="hv-brand" href={sitePath('/')} aria-label="Huayopata Viva, volver al inicio"><img className="hv-official-shield" src={sitePath('assets/identity/escudo-huayopata.webp')} alt="" width="34" height="34"/><span>HUAYOPATA VIVA</span></a><nav className="hv-global-links" aria-label="Navegación principal">{items.map(x=><a key={x.id} href={x.href} aria-current={section==='calendar'&&x.id==='calendar'||section==='home'&&active===x.id?'page':undefined}>{x.label}</a>)}</nav><a className="hv-global-cta" href={anchor('planifica')}>Prepara tu visita <span aria-hidden="true">↗</span></a><details className="hv-global-menu"><summary>Menú <span aria-hidden="true">+</span></summary><nav aria-label="Navegación móvil" onClick={e=>{const d=e.currentTarget.closest('details');if(d)d.open=false}}>{items.map(x=><a key={x.id} href={x.href} aria-current={section==='calendar'&&x.id==='calendar'?'page':undefined}>{x.label}</a>)}<a href={anchor('planifica')}>Prepara tu visita</a><div className="hv-global-sub"><small>HISTORIAS DEL VALLE</small>{[['abra-malaga','Abra Málaga'],['te','Té'],['cafe','Café'],['wamanmarka','Wamanmarka'],['comunidades','Comunidades']].map(([slug,label])=><a key={slug} href={sitePath('/descubre/'+slug)}>{label}</a>)}</div></nav></details></header>
}
