import {useEffect,useRef,useState} from 'react';
import {Camera,Maximize2} from 'lucide-react';
import photos from './territorial-media.json';
import './territorial-archive.css';
export default function TerritorialArchive(){
 const [selected,setSelected]=useState<number|null>(null),[failed,setFailed]=useState<string[]>([]);
 const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement|null>(null);
 useEffect(()=>{if(selected===null)return;const node=dialog.current;if(!node)return;node.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{node.close();document.body.style.overflow=previous;trigger.current?.focus({preventScroll:true})}},[selected]);
 const photo=selected===null?null:photos[selected];
 return <div className="hv-territorial-archive"><header><span>ARCHIVO DEL TERRITORIO</span><h3>Un lugar, muchas miradas.</h3><p>El pueblo, el agua y la memoria de piedra. Fotografías locales del archivo de Munihuayopata.</p></header><div className="hv-territorial-photos">{photos.map((p,i)=><figure key={p.id}><button onClick={e=>{trigger.current=e.currentTarget;setSelected(i)}} aria-label={'Ampliar fotografía de '+p.title}>{failed.includes(p.id)?<span className="hv-photo-fallback"><Camera aria-hidden="true"/><span>{p.title} · Fotografía temporalmente no disponible</span></span>:<img src={p.mobileUrl} alt={p.alt} width={p.width} height={p.height} loading="lazy" decoding="async" onError={()=>setFailed(f=>[...f,p.id])}/>}<span className="hv-photo-zoom"><Maximize2 size={18} aria-hidden="true"/></span></button><figcaption><small>{p.category}</small><h4>{p.title}</h4><p>{p.description}</p><a href={p.source} target="_blank" rel="noreferrer">Munihuayopata · Fuente y créditos ↗</a></figcaption></figure>)}</div><p className="hv-archive-license">Archivo publicado en 2015 · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a>. Versiones WebP redimensionadas; se conservan el encuadre y los rótulos originales. Estas imágenes muestran lugares, no celebraciones.</p>{photo&&<dialog ref={dialog} className="hv-gallery-lightbox" aria-label={'Fotografía de '+photo.title} onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null)}}><button autoFocus onClick={()=>setSelected(null)}>Cerrar ×</button><figure><img src={photo.url} alt={photo.alt} decoding="async"/><figcaption>{photo.title} · Munihuayopata · Archivo publicado en 2015 · <a href={photo.source} target="_blank" rel="noreferrer">Fuente documental ↗</a> · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a></figcaption></figure></dialog>}</div>
}
